### ISSUE TITLE
Spec export: in 3.7 with latest Measure Plugin stops working for some documents

### ISSUE THREAD

**Issue by bustablasta** [utom/sketch-measure#104]
After a few successful exports with the same document the spec export stopped working. 

First effect: only export of one single random slice of about 50 in the slices folder, nothing else, no html or js. 

Second effect after repeating the export: nothing. No "export complete" message, no reaction inside sketch, no exported files.

Had the same issue with the 3.5 version with only some documents.

**Comment by utom** [comment]
last version fixed
