### ISSUE TITLE
Cannot measure and generate SYMBOL spec in 3.7.1

### ISSUE THREAD

**Issue by yingyho4** [utom/sketch-measure#105]
Want to know if there are any solution to measure and generate Symbol SPEC. Since lots of UI elements are symbols, it is not convenient if we don't have this feature.

**Comment by srizon** [comment]
Maybe I wasn't clear about your question but I it's working on [symbol page](https://drive.google.com/a/creatrix.us/file/d/0B-5Jxyvd9i8PT2dwTUVmRmlmZjA/view?usp=drivesdk) just fine here.

**Comment by yingyho4** [comment]
I reproduce the issue as below:
https://dl.dropboxusercontent.com/u/6236427/Teresa/sketch_report_bug_measure01.mov
https://dl.dropboxusercontent.com/u/6236427/Teresa/sketch_report_bug_measure02.mov

**Comment by utom** [comment]
Try to update last version

**Comment by satinator** [comment]
icons cannot be exported or measure its hang in there for with popup. Ver 54.1
