### ISSUE TITLE
5/16/16 2:07:08.127 PM Sketch Beta[75865]: Exception: TypeError: style.fills().addNewStylePart is not a function. (In 'style.fills().addNewStylePart()', 'style.fills().addNewStylePart' is undefined)

### ISSUE THREAD

**Issue by robinraszka** [utom/sketch-measure#113]
5/16/16 2:07:08.127 PM 2. Measure size (Sketch Plugin)[75865]: TypeError: style.fills().addNewStylePart is not a function. (In 'style.fills().addNewStylePart()', 'style.fills().addNewStylePart' is undefined)
line: 244
sourceURL: /Users/robin/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/measure.sketchscript
column: 53

**Comment by utom** [comment]
Update last version of plugin

**Comment by robinraszka** [comment]
I'm using the latest version of the plugin.

**Comment by utom** [comment]
Are you sure? "version": "0.9.4.4"???

**Comment by robinraszka** [comment]
Ah, I see the fix from today now. Got it. Good stuff!

**Comment by rc1** [comment]
Getting this too. Using "0.9.4.4" and sketch "3.7.1"

**Comment by rc1** [comment]
`git checkout 5b0c64d4815af420735a03c294c286bb641d46d` solves it.
