### ISSUE TITLE
Create Overlay/Note broken in Sketch 3.8.1

### ISSUE THREAD

**Issue by stese** [utom/sketch-measure#114]
Since the Update of Sketch to 3.8.1, the functionality to create an overlay or a note is not longer working.

- There is not error message like the one, if you did not have selected anything shown
- After running the command to create an overlay, the screen is flickering but not folders/layers are created 
- The commands to measure the size or spacing is still working without any issue.

**Comment by utom** [comment]
try to update last version

**Comment by stese** [comment]
thanks - fixed in 0.9.4.4
