### ISSUE TITLE
Does not work for 3.8.1

### ISSUE THREAD

**Issue by aalokt89** [utom/sketch-measure#115]
plug-in isn't working for 3.8.1

**Comment by bfouillet** [comment]
Hello ! I have the same problem, it does not work with the new 3.8.1 version. If you could update the plugin it would be awesome. Thank in advance !

**Comment by alliv8** [comment]
Yea same. Not working for 3.8.2 either. It was working and now it just blinks.

**Comment by utom** [comment]
Try to update newest version or reset configs (settings > reset configs).

**Comment by alyssatucker** [comment]
It crashes Sketch whenever I try to Get Properties.

**Comment by utom** [comment]
@alyssatucker Do you try to update newest version or reset configs??????????

**Comment by alliv8** [comment]
Tried both. The screen flickers and nothing happens

**Comment by vtRex** [comment]
Same situation as alliv8,

**Comment by vtRex** [comment]
Try to reinstalled  plug-in

**Comment by alyssatucker** [comment]
I reinstalled it and it works now. Thought it wasn't that easy because it didn't appear under "Installed Plugins" in the Sketch Toolbox for some reason even though it was listed under Plugins in Sketch.
