### ISSUE TITLE
'Create Note' Not Working (Sketch 3.8.2)

### ISSUE THREAD

**Issue by Harkko** [utom/sketch-measure#118]
'Create Note' -feature doesn't seem to work in Sketch 3.8.2.

1. Make a new text layer on an artboard
2. Plugins > Measure > Create Note
3. Nothing happens ???

(sorry for the crappy gif, but I think you get the point)
![measure-note-issue](https://cloud.githubusercontent.com/assets/9257640/15643834/17642800-2658-11e6-8c7f-ddb9da7f38af.gif)

**Comment by utom** [comment]
last version of plugin???

**Comment by Harkko** [comment]
Yeeeep, ok so updating to the latest version of the plugin fixed this 😅  k thanx bye
