### ISSUE TITLE
Hide and show Measurements in Spec Export

### ISSUE THREAD

**Issue by c-pohl** [utom/sketch-measure#119]
Dear utom (and everyone else),

imho it would be an great advantage if it is possible to hide/show measures in Spec Export.
I would see an additional toggle in the topbar, next to "Toggle Notes": 
![spec_export-toggle_measures](https://cloud.githubusercontent.com/assets/1457704/15707185/a734c21e-27f7-11e6-9a2e-eef00245f325.png)
Maybe with another icon … ;)

Do you have any plans on making this available?

All the best
Christopher

**Comment by c-pohl** [comment]
Just for clarification:
I am talking about the measures which you add inside of sketch. Right now they are base64 decoded in `#screen`

**Comment by utom** [comment]
That's difficult thing!!! Do it too costly

**Comment by utom** [comment]
Do this very difficult
