### ISSUE TITLE
Export of Nested symbols specs is not clickable

### ISSUE THREAD

**Issue by bklaydman** [utom/sketch-measure#120]
In v0.9.4.3 I could export artboards to specs to generate HTML and the elements of the nested symbols were clickable. This was great. Not in v0.9.4.5 it is no longer the case. The nested symbols are treated as one block in sketch. This is wrong - I want to be able to measure inner elements. Could you please bring it back?

**Comment by utom** [comment]
try to last version and slice symbol artboard

**Comment by bklaydman** [comment]
It works great now. Can I ask for another feature? It would be great if we could also have the shared style name in export. Especially for the text styles it is very useful so that developers know what system style to apply to text such as Body, Footnote, Title 1, etc.
