### ISSUE TITLE
Shortcuts are missing 

### ISSUE THREAD

**Issue by rossul** [utom/sketch-measure#121]
Shortcuts are missing 
Sketch 3.8.3
<img width="702" alt="screen shot 2016-06-06 at 5 10 15 pm" src="https://cloud.githubusercontent.com/assets/8880151/15837990/d45dc8a6-2c09-11e6-977f-c0e8af8a64a4.png">

**Comment by nvenk** [comment]
Noticed the same, and came here to report :)

**Comment by utom** [comment]
Yep~ Because you have Invision Craft installed, so you can create custom shortcuts. http://www.sketchshortcuts.com/
