### ISSUE TITLE
Show position UI controller

### ISSUE THREAD

**Issue by prasad1287** [utom/sketch-measure#122]
THE ISSUE:
The "Show Position" controller being a drop down box, it’s sometimes annoying and takes two click for the user to select their desired option.

THE SOLUTION:

A multi tab controller with all the four position options upfront. The user clicks on their desired option and ultimately reduces one click each time they have change the option.

https://dribbble.com/shots/2764103-Sketch-Measure-Plugin-for-Sketch-UX-UI-Refinement

![artboard 1 copy](https://cloud.githubusercontent.com/assets/5609242/15886894/fc2670f8-2d7c-11e6-85ee-ede5a1498d8d.png)

**Comment by utom** [comment]
https://twitter.com/utom/status/739752834745413632

**Comment by prasad1287** [comment]
Nice one mate. When are you planning to release it?
