### ISSUE TITLE
URL Error with "/" in the Artboard name

### ISSUE THREAD

**Issue by halol** [utom/sketch-measure#123]
@utom 

Hi, I usually split artboards to different folders using naming convention e.g:
`Members/Details`
`Members/Add` New
so Sketch creates folder `Members` with to PNG's `Details.png` and `Add New.png`
But the URL for HTML goes crazy after Spec Export because of the `/` in Artboard name.

There is a possibility to replace `/` to whitespace or other symbol to avoid URL splitting problem

Cheers!

UPDATE:
Ok, I know what's the problem:
Artboard name: Members/Details
HTML file name: Members-Details.html
HREF attribute: Members/Details.html

So links and html names are different in this case. @

**Comment by halol** [comment]
Nail it (lame solution):

**Comment by utom** [comment]
@halol yep, I got it~ you can try Sketch Measure 2.0 beta 1. http://utom.design/measure/

**Comment by halol** [comment]
@utom new version works perfectly! Sketch 40.1 + latest Measure
