### ISSUE TITLE
Textfields on symbols not show their real content

### ISSUE THREAD

**Issue by qmarcos** [utom/sketch-measure#130]
**Tested on** 
Sketch 3.8.3

**Description**
When an artboard contains symbols with textfields inside them, when exporting all the instances of the symbol show the same text (the original one from the symbol) inside the content textarea at the properties panel of the viewer.

**Comment by utom** [comment]
Sorry, Sketch.app does not have this API.

**Comment by qmarcos** [comment]
Hi utom, thanks a lot for your answer.

Hope this will be added to the API soon. 
It'd be really useful for improving the workflow. If you have instance texts at the viewer (and not symbol texts) you don't need to open sketch to get final copys... for me it's the most interesting feature of the viewer... frontend devs don't need to have installed sketch or open it to get all the information they need.

**Comment by utom** [comment]
fixed it! you can't try to 2.0 beta 2 from http://utom.design/measure/

**Comment by qmarcos** [comment]
Yeah!
Really nice, and the 2.0 beta version is A W E S O M E!
Amazing job!
