### ISSUE TITLE
在3.9版下还是有问题

### ISSUE THREAD

**Issue by hanuse** [utom/sketch-measure#133]
用新版resizing功能后，调整 symbol 大小后，生成的标记文件还是原始的symbol尺寸，页不是调整后的symbol尺寸

**Comment by utom** [comment]
没太明白~

**Comment by hanuse** [comment]
可惜不能截图，要么发个链接 [新功能演示](http://www.zcool.com.cn/article/ZNDE1Mjg0.html) ，使用此新功能后生成的标记文件标记不正确

**Comment by utom** [comment]
哦, 我明白问题是什么了~

**Comment by utom** [comment]
下载最新版~
