### ISSUE TITLE
spec export not working in Sketch version 39 (31667)

### ISSUE THREAD

**Issue by pratikjshah** [utom/sketch-measure#134]
Hi There,

I have update my **sketch** to current **version 39** and after that "**spec export**" feature is not working.
The process I am following is..

1. Select the art-board/s
2. Go to Plugins --> Measure -->  Spec export
3. It asks for Resolution setup

but after selecting a resolution nothing happens.. the file save dialog never appears! 

Please fix this issue! As "**Spec export**" is the feature I use in my day2day work. I love this plugins. You guys rock \m/

**Comment by utom** [comment]
Please, update to last version. 2.0 beta 2 is working.
