### ISSUE TITLE
2.0版在3.8.3版中导出不了任何东西

### ISSUE THREAD

**Issue by hanuse** [utom/sketch-measure#136]
在3.8.3版中，用2.0版本中的Spec Export 导出是空的，什么文件都没有，文件夹都没有

**Comment by AquaHacker** [comment]
1.使用 旧版插件。我保留了一份 3.8.3可用版本，需要的可以发你；
2.使用 最新版 Sketch39 配合 Measure 2.0

**Comment by hanuse** [comment]
旧版插件我有备份，多谢，因考虑到其他插件还不支持3.9，所以暂时没升级到3.9

**Comment by utom** [comment]
不支持, 3.8.3~

**Comment by utom** [comment]
不支持, 3.8.3! 因为39版本新特性, APIs 冲突无法规避.
