### ISSUE TITLE
Can't Use Plugin After Sketch Update to 3.9

### ISSUE THREAD

**Issue by jmccanna** [utom/sketch-measure#137]
Since I've updated to Sketch to 3.9, the plugin doesn't work. I've tried every option, both from the menu bar and from keyboard shortcuts, but it doesn't respond, unfortunately. Hope this gets resolved since I absolutely love this plugin!

Thanks!

**Comment by salux** [comment]
I'm having trouble, too. Here's the error I see in the Console:

```
7/22/16 12:51:42.862 PM Settings (Sketch Plugin)[14960]: ReferenceError: Can't find variable: SMModalView
line: 817
sourceURL: /Users/username/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript
column: 32
```

That file imports common.js right away, so the error is actually there. It looks like the offending line/block (it's one of a bunch of arguments) is:

`panel = [[SMModalView alloc] initWithHtmlPath: path frame: frame]`

**Comment by utom** [comment]
Sorry, I need some times to fix it~ (X.X)

**Comment by utom** [comment]
Try to last version, please feedback to me:D
