### ISSUE TITLE
Export of the Shared Style Name

### ISSUE THREAD

**Issue by bklaydman** [utom/sketch-measure#139]
It would be great if we could also have the shared style name in export. Especially for the text styles it is very useful so that developers know what system style to apply to text such as Body, Footnote, Title 1, etc..

Not a bug, but really nice to have. The sketch measure plus (a version of based on this plugin) used to do this. 

Thank you for an awesome product!!!

**Comment by utom** [comment]
👍

**Comment by utom** [comment]
Update last version, 'Get Property' > 'Style name' and 'Spec Export'
