### ISSUE TITLE
Nested symbols support

### ISSUE THREAD

**Issue by bklaydman** [utom/sketch-measure#140]
I can see that I can select items within symbols, but where symbol is nested more than 2 levels, I can only select it as a group and cannot access the inner elements. It would be great if I could access all nested symbols (n-levels) in the specs.

Again, thank you so much for all your work and quick updates. Your plugin rocks!!!

**Comment by utom** [comment]
Spec export?? or other?

**Comment by bklaydman** [comment]
Just the spec export

**Comment by utom** [comment]
try to last

**Comment by bklaydman** [comment]
Thank you, thank you, thank you!!!
