### ISSUE TITLE
[Feature Request] Select whole page for export

### ISSUE THREAD

**Issue by bklaydman** [utom/sketch-measure#141]
Rather than selecting individual artboards for Spec export, it would be great to be able to select all artboards within a page if selected. I'm talking about the same UI as we currently have, but having a checkmark next to the page name to quickly select or unselect all artboards within a page.

Again, thank you for the great plugin.

**Comment by utom** [comment]
filter "page name", and "select filter". you can try this~

**Comment by bklaydman** [comment]
No that is not what I meant. Imagine the document with 10 pages, but I only want to create specs for 8 of them. Right now I have to select all and then go to other 2 pages and deselect the art boards on each of these pages manually. What I want is a checkbox next to the page name in export dialog to quickly select all artboards within page. Could you reopen the issue please?
