### ISSUE TITLE
Beta UI - Panel workflow slowdown

### ISSUE THREAD

**Issue by hellonicolas** [utom/sketch-measure#142]
Hi there!

Super excited to see a UI take form for Sketch Measure. Unfortunately it's slowed down our workflow quite a bit when going through a lot of redline tasks:

**The original process:**
* Keyboard shortcut to run a command, and that's it!

**New process:**
* Run keyboard shortcut
* Every time you run a Measure command, the new UI panel shows up and you have to click or tap "Mark" to actually create the measure elements (Enter or other keyboard shortcut does not work)
* Repeat that process hundreds of times and start to lose your mind

**Some ideas for making the panel workflow more efficient:**
* Have a modifier shortcut that will run a command WITHOUT the panel (and retain your last settings). If I'm setting the width and height the same way for 100 elements, why do I need to specify that every time?
* Alternatively: the Sketch Measure UI could live as global, dockable panels (note the way Invision  has set up their "Craft" plugin). The next time you run a command, it will use those global settings (maybe it could show the panel the first time you run a command in a Sketch document?).
* Allow a keyboard shortcut to choose "Mark" instead of having to click the button in the panel.

Oh, and thank you for making such a useful plugin :)

**Comment by utom** [comment]
@hellonicolas Thank you so much for your continued help and support, and I agree with you more. 
There is a good way:
* Select multiple layers to mark (not spacing)
* Press "enter" shortcut to mark in the panel

**Comment by utom** [comment]
Next version 2.1 will add "Lite size" and "Lite spacing"

**Comment by hellonicolas** [comment]
@utom Awesome, looking forward to playing with that :) Thank you!

**Comment by utom** [comment]
@hellonicolas next version 2.1 
![21](https://cloud.githubusercontent.com/assets/761468/17631789/1ac995ea-60f8-11e6-81d8-b63cf658d1e8.gif)
