### ISSUE TITLE
Spec Export doesn´t work for me. At all!

### ISSUE THREAD

**Issue by Tobabahopp** [utom/sketch-measure#145]
Hi Utom,

first, thank you for your great work :)
running OSX 10.11.6 (El Capitan) I tried everything to activate the Spec Export - doesn´t work.
I deleted and reinstalled Sketch completely, tried their BETA - even with Your latest BETA-Plugin...

Please - help!

Sincerely,
Tobi

**Comment by utom** [comment]
Sketch version?

**Comment by jrbondesign** [comment]
I have the same issue - the plugin will create the folder but no html files are created.

OS X 10.11.6
Sketch Version 39.1 (31720)

**Comment by Tobabahopp** [comment]
39

Am Dienstag, 26. Juli 2016 schrieb utom :

**Comment by jrbondesign** [comment]
Cancel that.. i'm using the beta and all is working as expected. The older measure plugin didn't uninstall correctly and I was using that to test. Sorry for the confusion - I'm all good! Thanks!

**Comment by HolaMan** [comment]
I encounter the same issues while exporting all, all assets and screenshot is created but no index.html file
sketch 39.1
OSX 10.11.3

**Comment by utom** [comment]
@HolaMan What's Sketch Measure version?

**Comment by JefrinArun** [comment]
Hi,
I am using Sketch Version 39.1. My sketch export generator and Icon font plugins are not working in this version. Haven't checked other plugins. it was working perfectly in version 38. Please help.

Thanks
Jefrin

**Comment by utom** [comment]
@JefrinArun What's Sketch Measure version? current version is 2.0 beta 5

**Comment by JefrinArun** [comment]
@utom How to find Sketch Measure version? From "About Sketch" I have only this detail. i.e Version 39.1 (31720)

**Comment by utom** [comment]
@JefrinArun  ... ... `Plugins` > `Manage Plugins...`

**Comment by JefrinArun** [comment]
![image](https://cloud.githubusercontent.com/assets/20638055/17292402/69e90470-5807-11e6-8ca2-9fe54566e404.png)
This is my manage plugin's screenshot

**Comment by utom** [comment]
@JefrinArun so... I can't found the name "Sketch Measure"... Are you sure you install is "Sketch Measure"?

**Comment by JefrinArun** [comment]
@utom, Thanks. My question was regarding "sketch export generator" and "Icon font" plugins which are not working in latest sketch version.

**Comment by utom** [comment]
@JefrinArun OK, let me see~ waiting

**Comment by utom** [comment]
@JefrinArun "Sketch Export Generator" [updated](https://github.com/kang-chen/sketch-export-generator/commit/8976fde23b50c260ea6f263f3adca21a8648b0a4) at 4 days ago.

**Comment by JefrinArun** [comment]
@utom thanks a lot for your support. Updated sketch export generator and it is working.

**Comment by bananica** [comment]
If you select just 1 artboard and click "spec export" nothing happens, you have to select at least 2 artboards for it to work.

**Comment by utom** [comment]
@bananica Let me check~ thank you so much for your feedback.

**Comment by giuseppebergman** [comment]
Same problem here with Sketch 39.1 and Sketch Measure 2.0.3 (Mac OS 10.10.5)
Tried with 1 and 2 artboards (461 and 1015 layers)
Only the "assets" folder is generated.
Here's the log:

```
21/08/2016 17:30:04,401 Sketch[1732]: Info: {
    column = 62;
    line = 2444;
    sourceURL = "/Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure v2.0.3.sketchplugin/Contents/Sketch/mark.sketchscript";
}

21/08/2016 17:30:04,401 💎 Spec Export (Sketch Plugin)[1732]: TypeError: undefined is not a function (evaluating 'textLayer.stringValue()')
line: 2444
sourceURL: /Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure v2.0.3.sketchplugin/Contents/Sketch/mark.sketchscript
column: 62

21/08/2016 17:30:29,000 kernel[0]: process Sketch[1732] caught causing excessive wakeups. Observed wakeups rate (per sec): 611; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 47513
21/08/2016 17:30:29,865 spindump[677]: Saved wakeups_resource.diag report for Sketch version 39.1 (31720) to [path]/Sketch_2016-08-21-173029_MP-Ion.wakeups_resource.diag
```

Any help would be much appreciated, as the client is waiting for the specs…

Thanks in advance.
