### ISSUE TITLE
Feature request: URL for each page/artboard

### ISSUE THREAD

**Issue by mscholtus** [utom/sketch-measure#146]
Hi there,

The new UI is great, thanks for all the effort you’re pouring into this!

In the old UI, multiple HTML-files were generated per artboard. We generated Sketch Measure exports for all artboards on each page, page by page. We used this to our advantage by linking to specific artboards so that our dev team could easily reference specific parts of the UI.

In the new UI, it’s easy to generate exports for the full document. This great and saves us a lot of time and minimises the potential for errors. However with only one index.html file exported, we lost the ability to reference a specific artboard on a specific page by linking to it directly. 

I fully understand that this way of exporting is much more efficient, but is there a way to add the ability to link to a specific page and/or artboard in de new UI? Perhaps by using anchor links and `window.location.hash` to trigger the selection of an artboard?

**Comment by hanuse** [comment]
我也觉得，界面漂亮，好用。这个新版我一直没正式使用，没发现这个问题，多页测试了下，发现只生成一个文件，这样不方便以后替换单独页面，如果文件有100页，修改一页后又要全部导出一次，这样影响效率。再次感谢 utom 开发的产品！

**Comment by utom** [comment]
Added and I close it

**Comment by c5inco** [comment]
I notice now that when using the hash in the link, the left panel to switch artboards is hidden by default.  However, when you go to index.html, the panel expands by default.  Is there a way to fix that?
