### ISSUE TITLE
图片切图查看时，同名称的可否只显示一个？

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#147]
![image](https://cloud.githubusercontent.com/assets/20694736/17200024/59ceb482-54b4-11e6-9b09-b937c852ca6b.png)

**Comment by utom** [comment]
建议每一个重复使用的图标或切图, 都放到 symbols 当中.
* 一方面以后可以方便修改
* 另一方面可以导出的时候不会出现重复的现象, 而且还能从切片列表当中快速找到位置

参见: https://pan.baidu.com/s/1geZNxbP

**Comment by YolandaKim** [comment]
你好，这些图片就是创建的Symbols。都是用一个符号元件的。

**Comment by utom** [comment]
我看看你的切片在图层怎么设置的?

**Comment by YolandaKim** [comment]
![image](https://cloud.githubusercontent.com/assets/20694736/17200629/9d76bd24-54b9-11e6-85d7-101a26161c75.png)
![image](https://cloud.githubusercontent.com/assets/20694736/17200635/a5b1ae54-54b9-11e6-86c2-6ca106ce7b78.png)
![image](https://cloud.githubusercontent.com/assets/20694736/17200644/aed2e3c2-54b9-11e6-931d-8fce4636eb4d.png)

**Comment by utom** [comment]
一般是在 symbol 画板上做设置切片, 或者新建一个 slice 在 symbol 画板当中

**Comment by YolandaKim** [comment]
您的意思是这样？
![image](https://cloud.githubusercontent.com/assets/20694736/17200671/e9fc8002-54b9-11e6-8506-920c087446c1.png)

**Comment by utom** [comment]
上面是对的, 不过我刚试了下的确有问题

**Comment by YolandaKim** [comment]
我之前一直是在symbol里做slice
![image](https://cloud.githubusercontent.com/assets/20694736/17200702/26343268-54ba-11e6-913e-9fb625b0b56c.png)

**Comment by YolandaKim** [comment]
嗯嗯 好的  那我等待修复 谢谢您

**Comment by utom** [comment]
over了
