### ISSUE TITLE
html页，无法正常预览！

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#149]
我重新下载插件了！
但是导出的html，打开，存在问题：
画板无法正常查看规范：右侧没有显示内容 是空的，左侧点击画版无反应；
点击“切片、颜色”都无反应

**Comment by utom** [comment]
什么浏览器

**Comment by YolandaKim** [comment]
Safari

**Comment by YolandaKim** [comment]
![qq20160729-0 2x](https://cloud.githubusercontent.com/assets/20694736/17238699/78de4946-5590-11e6-9e51-1576511e61e5.png)

**Comment by YolandaKim** [comment]
utom，帮我看看怎么办好，昨天插件更新后，使用出现这个问题。
![qq20160729-0 2x](https://cloud.githubusercontent.com/assets/20694736/17238912/5f1f9e54-5592-11e6-9371-0a17754adfb7.png)

**Comment by utom** [comment]
今天更新一下呢?~ 顺便可以把导出的东西打包给我吗? utombox@gmail.com

**Comment by YolandaKim** [comment]
已打包发送至邮箱，请查收！辛苦了！

**Comment by utom** [comment]
问题已经fixed, 稍后上传.
希望你检查一下, 这两个图层我想看看是什么回事
lvxingquan_icon_28px
touxiang_nor_30px

**Comment by YolandaKim** [comment]
与这两个symbols有关系嘛？不应该哈！


![qq20160729-3 2x](https://cloud.githubusercontent.com/assets/20694736/17241981/72164110-55a7-11e6-8322-b3cb8db94eed.png)

![qq20160729-2 2x](https://cloud.githubusercontent.com/assets/20694736/17241989/7d95f6de-55a7-11e6-81a7-8c3d88da9625.png)

![qq20160729-1 2x](https://cloud.githubusercontent.com/assets/20694736/17241991/83c15ed6-55a7-11e6-99c5-5ee5f2b063d0.png)

**Comment by utom** [comment]
切片是怎么设置的?

**Comment by YolandaKim** [comment]
utom，我给你发了邮件！请您查收！
也许，我找到原因了，可是还是不确定正确的做法，请您看下邮件，给我个答复好吗？谢谢您！

**Comment by utom** [comment]
fixed
