### ISSUE TITLE
能否一键显示/隐藏所有画板里的Notes？

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#150]
![image](https://cloud.githubusercontent.com/assets/20694736/17203087/f0582904-54cf-11e6-837b-1d0d8b0872a1.png)

画板里添加的Notes，可否有一键显示和隐藏所有功能，notes多了，想查看和隐藏有些不方便！

**Comment by utom** [comment]
"Hide marks"

**Comment by YolandaKim** [comment]
一键显示呢？

**Comment by utom** [comment]
Show marks

**Comment by YolandaKim** [comment]
![qq20160729-0 2x](https://cloud.githubusercontent.com/assets/20694736/17243827/42646514-55b1-11e6-9aba-69435899818b.png)
不好意思，没有找到！

**Comment by utom** [comment]
应该是再按一下 hide marks
