### ISSUE TITLE
Keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by spiritjp** [utom/sketch-measure#151]
Sketch 39.1 Measure 2.0 beta 4, keyboard shortcut doesn't work.
It's  too inconvenient without shortcut now. Please fix it up. Thank you.

**Comment by utom** [comment]
Is the plugin Craft on your Sketch?  Craft interrupts Sketch Measure's keyboard shortcuts. Try to create custom shortcuts in mac keyboard.
![shortcut](http://utom.design/shortcut.gif)
