### ISSUE TITLE
[Feature Request] Confirm popup with Enter key on keyboard

### ISSUE THREAD

**Issue by revelt** [utom/sketch-measure#152]
Thanks for this amazing plugin.

Is it possible to make it accept ENTER keyboard key as confirmation to accept whatever is on the popup?

(I'm clicking CTRL+SHIFT+] to add vertical height measure, then popup appears for the first time. That's this popup I'm talking about.)

I know, the popup remembers the setting after the first click and doesn't appear anymore for the session, but it would be even faster if I could avoid using keyboard at all.

🦄  🌈 🦄  🌈

**Comment by utom** [comment]
Added and I close it

**Comment by revelt** [comment]
Thank you! It does work, I just tested the latest release 😀
