### ISSUE TITLE
Request: vh/vw units, 16px REM

### ISSUE THREAD

**Issue by kevinSuttle** [utom/sketch-measure#153]
vw/vh: https://css-tricks.com/viewport-sized-typography/

**Comment by utom** [comment]
"16px REM" already supports, choose "CSS Rem 12px" and edit scale input to "16".
but vw/vh is not

**Comment by FoxBJK** [comment]
"16px REM" doesn't work for this. VW/VH calculations don't relate to other elements' font sizes, so we can't just take the numbers calculated from "16px REM", because it doesn't correlate to VW/VH at all. Can we reopen this?
