### ISSUE TITLE
html页预览，切片显示问题！

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#154]
![qq20160729-6 2x](https://cloud.githubusercontent.com/assets/20694736/17243086/584c5796-55ad-11e6-83ae-874b54dbc33b.png)

似乎，不单单是一个界面上的问题。是所有画板界面中，只有第一个symbols才有显示切片，其他界面相同元素右侧都不显示呢。

**Comment by utom** [comment]
文件发我看看

**Comment by utom** [comment]
不用了, 找到问题了

**Comment by YolandaKim** [comment]
哦哦 好的 ！
