### ISSUE TITLE
切片显示问题！

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#155]
![1](https://cloud.githubusercontent.com/assets/20694736/17244300/bb8ed580-55b3-11e6-9694-3af434b94a6c.png)
![2](https://cloud.githubusercontent.com/assets/20694736/17244301/bbd58b9c-55b3-11e6-98d3-6dbb271bcdcd.png)

**Comment by utom** [comment]
这个不是问题, 你要把切片放在这些图层最前面...
