### ISSUE TITLE
[Feature Request] In export select multiple page which would select all artboards on these pages for export

### ISSUE THREAD

**Issue by bklaydman** [utom/sketch-measure#156]
Imagine the document with 10 pages, but I only want to create specs for 8 of them (all artboards on every selected page). Right now I have to select all and then go to other 2 pages and deselect the art boards on each of these pages manually. What I want is a checkbox next to the page name in export dialog to quickly select all artboards within that page, so I can select all first and quickly unselect all artboards on pages I don't want to export. Think of not wanting to export symbols, the title, and helper pages in your designs (each has many artboards).

**Comment by utom** [comment]
Try to last version, I'm waiting your feedback.

**Comment by bklaydman** [comment]
Yes it is the right direction. There is a bug though - when I select all I expect pages also be selected. But this is very close!!! Thank you!

**Comment by bklaydman** [comment]
Just checked the latest update. It is now perfect - thank you so much!!!
