### ISSUE TITLE
Spec export to a single HTML file

### ISSUE THREAD

**Issue by Steffen72** [utom/sketch-measure#157]
In the previous stable version, we were able to export our spec to a single HTML file, with every resource needed inlined in this file. This HTML was self-contained, meaning: no other resources (files) were needed to display all the content. This was very convenient.

With version 2.0 beta, export always creates an additional _preview_ directory containing part of the images that were previously inlined. Some images are still inlined in the HTML file, though. If we distribute our information now, we need to pack it up as ZIP, and on the client's side someone has to download and unzip it first, instead of just opening a HTML link from JIRA.

Is there a reason for this change in behaviour? Is there some setting to switch behaviour of your plugin back to the previous version's  (that is: to the single, self-contained HTML file)?

**Comment by utom** [comment]
Update last version, Export and uncheck "Advanced mode".
