### ISSUE TITLE
Feature request: Make replacing the object measured by Lite width/height a setting

### ISSUE THREAD

**Issue by mi-mi-mi** [utom/sketch-measure#158]
Hi,

I'm not sure how big is this user case, but I rarely need both dimensions when measuring an object. It's either width or height. This happens because my layouts are complex, and I prefer to avoid crowding every object with both measurements. Since many objects repeat in a layout, I cherry pick where do I show widths and where heights.

90% of the time I use Lite width / height because it's keyboard only and I don't need to deal with the Dimensions popup to select which dimension I would need. Because the Lite width/height always replaces the object, I work around that by first copy+pasting the object I want to measure.

Could you please make replacing the object a toggle in the settings? That would eliminate the need to copy/paste every time, cutting in half the effort.

Thank you for doing such an awesome job with this plugin!

Please like if you consider this useful.

**Comment by utom** [comment]
Wow~ Great idea!
I have a better idea, make replacing copy and pasting to use `CMD` + `D` and change Lite feature shortcuts to `CMD` +` [` and `CMD` + `]`
