### ISSUE TITLE
sketch exporting but showing blank screen htmls

### ISSUE THREAD

**Issue by prahalad-S** [utom/sketch-measure#159]
I can see thumbnails in leftside navigation. but while clicking on it I can see white blank screen in middle. There are elements and if I select any element on that white screen it also shows its properties in the right side panel. But why its displaying the blank white screen? 
While exporting if I dont select the advanced option then its exporting the html pages correctly but its not exporting the thumbnails. how to get this solved? screenshot attached below
![slice](https://cloud.githubusercontent.com/assets/3490600/17318913/ad2c17ae-58a7-11e6-8e94-39f8564e1317.png)

**Comment by utom** [comment]
Hello, Can you send the exported all files to me? Let me check. Is this color not my current version? looks better

**Comment by pranyreddy** [comment]
Even am facing the same issue, all the HTML generated pages are showing blank. But working fine when opened through local disk.

**Comment by utom** [comment]
@pranyreddy hello, can you send me the all exported file? utombox@gmail.com. thank you for your feedback.

**Comment by prahalad-jake** [comment]
I got this worked by one method, but it did not work for another file again. All I did is, deleted all other pages including symbols except the page which I wanted to export for redlines. After redlines got exported well, immediately  I have undone by "cmd+z" to bring back my deleted pages and saved the sketch file. I will send you a duplicate file by the end of the day which was not exported to redlines even by using this trick.

**Comment by prahalad-jake** [comment]
Here are the samples I have attached in zip files in both versions. One is with advanced option selected and other is without advanced option. Below I have attached the screenshots which I 'm unable to view in html pages after converting them to redlines. I just imported those  jpeg images in sketch and exported but still cant view them in output.
![main - 01 new -landing - screen 3 level 1](https://cloud.githubusercontent.com/assets/3490600/17366044/ca8f0450-59a6-11e6-8b2d-3ceeeba1888f.png)
![main - 02 new -landing - screen 3 level 2](https://cloud.githubusercontent.com/assets/3490600/17366045/ca964ef4-59a6-11e6-97c4-a73aa86e311e.png)


[demo_files.zip](https://github.com/utom/sketch-measure/files/399465/demo_files.zip)

**Comment by prahalad-jake** [comment]
@utom @pranyreddy 

Guys, I fixed it. I think it may not be a bug in the plugin. After struggling for hours with many different variations by deleting, adding etc.. I just renamed the artboards names. Redlines is not exporting properly coz of those naming in artboards like  "-" or "()" if included. I removed the "-" and "()" and exported again and it worked like a charm! please try this, it may work whom its not working...Gud luck!...
see attached screenshot.

![slice_w](https://cloud.githubusercontent.com/assets/3490600/17366966/91a2a822-59ab-11e6-8c77-8ce8b69ab81a.png)


Thank you.

**Comment by utom** [comment]
the name will convert to slug.

**Comment by utom** [comment]
trying

**Comment by utom** [comment]
fixed v2.0.1
