### ISSUE TITLE
Bug: Range or index out of bounds

### ISSUE THREAD

**Issue by mscholtus** [utom/sketch-measure#160]
When exporting an artboard with one specific text layer the export fails. I’ve attached the console output and the affected layer isolated in a sketch file below.

This is probably a weird edge case as the text layer seems bugged in Sketch: I can’t select any font from the typeface menu.

[exportcrash.sketch.zip](https://github.com/utom/sketch-measure/files/399608/exportcrash.sketch.zip)

```
03/08/16 15:52:13,243 Sketch[2611]: *** WebKit discarded an uncaught exception in the webView:didFinishLoadForFrame: delegate: <MOJavaScriptException> TypeError: null is not an object (evaluating 'COScript.currentCOScript().setShouldKeepAround_')
03/08/16 15:52:16,462 Sketch[2611]: Exception: *** -[NSConcreteTextStorage attribute:atIndex:effectiveRange:]: Range or index out of bounds
03/08/16 15:52:16,462 Sketch[2611]: Info: (null)
03/08/16 15:52:16,462 💎 Spec Export (Sketch Plugin)[2611]: *** -[NSConcreteTextStorage attribute:atIndex:effectiveRange:]: Range or index out of bounds
```

Sketch version: 39.1
Sketch Measure plugin: 2 (just downloaded the latest version)

**Comment by utom** [comment]
fixed. v2.0.1

**Comment by utom** [comment]
Thank you so much
