### ISSUE TITLE
发现生成的links中的文件内没有标记内容

### ISSUE THREAD

**Issue by hanuse** [utom/sketch-measure#162]
你好！

发现生成的links中的html文件内没有标记内容，标记内容还是在index.html中，这样没有作用。
例如：我做了将近100页，我修改了一页，生成文件后替换links里的那页文件，打开index.html后，替换过的页面标记还是没有变化。
可否将各页的内容分到links内的页面中，而不是集中在index.html 中。这样单独替换几页就会可以了，而不用重新导出所有页面。
 希望可以实现，感谢！

**Comment by utom** [comment]
那你就把高级模式勾去掉

**Comment by hanuse** [comment]
谢谢，其实我是想要高级模式，又要可以单独替换页面的功能
