### ISSUE TITLE
Artboard list reversing

### ISSUE THREAD

**Issue by iamaaronmartin** [utom/sketch-measure#169]
So, my artboards are in order from top to bottom in my Sketch file, but they're listed in the reverse order in Measure's HTML output.

I found a solution I'd like to suggest, and it's super easy. I've implemented it myself in my local copy of the plug-in, but having it as a Setting should be easy enough to implement, and it's done using CSS only.

Here's the added code:
```
ul.artboard-list {
	display: flex;
	flex-direction: column-reverse;
	}

.artboard-list li {
	flex: 0 0 auto;
	}
```

Hopefully this helps.

**Comment by utom** [comment]
I reverted it, css is not better, must be using javascript to do it. thank you so much

**Comment by iamaaronmartin** [comment]
Not better than what?

**Comment by utom** [comment]
I tried using the code, I found an issue the first index at the end of the list.

**Comment by utom** [comment]
2.1 is now named sort
