### ISSUE TITLE
[Feature request] Always floating window

### ISSUE THREAD

**Issue by songcarver** [utom/sketch-measure#172]
I'd love a panel that stays open and floats, much like the Magic Mirror plugin, for example. Something like a tabbed view for the various functions. 

This would add a lot of efficiency, for me, rather than opening and closing the window (and remembering which one has the piece I need)

**Comment by utom** [comment]
Next 2.1 version

**Comment by utom** [comment]
@songcarver next version 2.1 
![21](https://cloud.githubusercontent.com/assets/761468/17631789/1ac995ea-60f8-11e6-81d8-b63cf658d1e8.gif)

**Comment by songcarver** [comment]
woohoo! Thanks @utom
