### ISSUE TITLE
[Feature Request] Overwrite changed artboard in advanced mode without deleting others in "index.html"

### ISSUE THREAD

**Issue by a-u-me** [utom/sketch-measure#173]
Hello!
You made incredible tool that sometimes nicer for me than proprietary Zeplin.
But when I change something in current artboard how can I add this only artboard to previously exported full project without overwriting / deleting others from "index.html"?

**Comment by utom** [comment]
try to uncheck `Advanced mode`

**Comment by a-u-me** [comment]
Wait please — but how to add this non-advanced exported %artboardName%.html to main index.html in order to view entire project with this latest changes?
