### ISSUE TITLE
Broken in Sketch 39.1

### ISSUE THREAD

**Issue by giuseppebergman** [utom/sketch-measure#178]
Only "assets" subfolder is generated.
Running Sketch 39.1, Sketch Measure 2.0.3 on Mac OS 10.10.5.
Tried with 1 and 2 artboards (461 and 1015 layers)
Here's the log:

```
21/08/2016 17:30:04,401 Sketch[1732]: Info: {
    column = 62;
    line = 2444;
    sourceURL = "/Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure v2.0.3.sketchplugin/Contents/Sketch/mark.sketchscript";
}

21/08/2016 17:30:04,401 💎 Spec Export (Sketch Plugin)[1732]: TypeError: undefined is not a function (evaluating 'textLayer.stringValue()')
line: 2444
sourceURL: /Users/Me/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure v2.0.3.sketchplugin/Contents/Sketch/mark.sketchscript
column: 62

21/08/2016 17:30:29,000 kernel[0]: process Sketch[1732] caught causing excessive wakeups. Observed wakeups rate (per sec): 611; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 47513

21/08/2016 17:30:29,865 spindump[677]: Saved wakeups_resource.diag report for Sketch version 39.1 (31720) to [path]/Sketch_2016-08-21-173029_MP-Ion.wakeups_resource.diag
```

Any help would be much appreciated, I'm panicking a bit here as my client is waiting for the specs…

Thanks in advance for your work.

**Comment by giuseppebergman** [comment]
It seems it's something on my artboard that causes the bug. Another artboard exported just fine (with Sketch 39.1 and plugin downgraded to 2.0 beta 1).

**Comment by giuseppebergman** [comment]
Ok, I found what caused the bug: I moved a subfolder of custom layers inside an "NOTE" folder generated by the plugin, beside the "text" and "note-box" layers. Once my subfolder deleted, the artboard exported just fine.

**Comment by utom** [comment]
Yep, known issues
