### ISSUE TITLE
导出后，标注错位！

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#181]
<img width="301" alt="2016-08-26 12 10 11" src="https://cloud.githubusercontent.com/assets/20694736/17993842/20464584-6b86-11e6-8cea-66618a19247f.png">
现在新版的导出的，如图，很多都有这样的问题，不准哈 错位！！

**Comment by utom** [comment]
Symbol 画布里的图层, 不要超出 Symbol 画布范围.

**Comment by YolandaKim** [comment]
不要超出 Symbol 画布范围.，也包括里面的Note吗？   有时想偷懒避免写重复的note就放里面了！
