### ISSUE TITLE
导出规范问题

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#184]
还是上次的问题，导出规范后，标注显示的不准确
<img width="334" alt="2016-08-27 23 09 27" src="https://cloud.githubusercontent.com/assets/20694736/18028227/7efc8d1a-6cab-11e6-92f6-91d0df80bd37.png">
您说Symbols的画板里面不能有图层元素超出画板范围，真的很头痛，之前似乎不曾因此出现这个问题。
我也仔细检查过Symbol没有超出画布的，可是导出规范，中会出现差别，不是宽度少了就是高度显示的不对，到底怎么回事？为何之前不曾因此困扰呢？

**Comment by YolandaKim** [comment]
是不是现在设计时".5"的尺寸或者距离都不可以了？

**Comment by hanuse** [comment]
不知你说的是不是和我之前碰的到情况一样，后来找到原因：虽然symbols中的尺寸是24x24,但在画板上你的图标拉变形了，变成了25x24，所以导出的尺寸是以画板上的为准，而不是symbols中的尺寸，你再检查下你的文件。

**Comment by YolandaKim** [comment]
hanse 你好，我检查过，我的symbols的大小是25*25 里面icon也是的；且symbols也没有拉变形。我来回试错找原因，发现我的symbols没问题，可能和symbols的“X/Y坐标有.5数值”产生导出后偏差的问题，因为我把“.5”去掉后我导出后，标注就是25*25显示正常了。

现在，我很纠结想问下u大，具体是何原因呢？是插件原因还是我的原因？

而且在做symbols时，难免里面的元素会擦出symbols设置的画布大小，现在似乎symbols里面的元素超出symbols的画布也会引起导出标注的偏差。

真的希望U大能解决这个问题，真的很困扰！

**Comment by hanuse** [comment]
最好上传个有错的原文件，这样就能找到真正原因

**Comment by YolandaKim** [comment]
[test.zip](https://github.com/utom/sketch-measure/files/441509/test.zip)
U大帮我看看问题
<img width="593" alt="caf513fe-0b7d-4881-a356-7ae9cfe331ec" src="https://cloud.githubusercontent.com/assets/20694736/18038553/44b95b5c-6dcc-11e6-8e53-7aa2df86d547.png">
我目前认为是这个.5距离造成的问题！

**Comment by utom** [comment]
应该是四舍五入了~

**Comment by YolandaKim** [comment]
U大，是不是如我猜的.5这个问题所造成导出后的标注尺寸显示不准确了？
U大，能否不要四舍五入呢？
还有很困扰的问题和Symbols里面的元素超出画布的，可否也不计较呢，真的很痛苦！

**Comment by utom** [comment]
我想想可能也不是四舍五入的问题

**Comment by YolandaKim** [comment]
坐等解决的结果

**Comment by utom** [comment]
暂不处理~
