### ISSUE TITLE
mark properties点击以后直接标注所有信息

### ISSUE THREAD

**Issue by xqchiyyy** [utom/sketch-measure#187]
如何选择需要的信息而不是全部标注？

**Comment by utom** [comment]
Hello, @xqchiyyy 按住 `Option` 点击图标

**Comment by xqchiyyy** [comment]
您说的按住option选择图标，操作以后依旧没有跳出选择面板。除了标注的信息还有标注的位置，上下左右的选项都无法自行选择了。正常的步骤是选择一个要标注的元素然后shift+control+4对吧？以前的版本没有遇见过这个无法选择的问题，现在shift+control+4以后，标注对象是文字的话就直接输出6种信息，至于您说的按住option唤出选项面板如何操作呢，麻烦解释的稍微详细一些，谢谢！

**Comment by utom** [comment]
选中要标注的图层, 按住 `option`, 点击面板的图标...

**Comment by utom** [comment]
按住不是按一下

**Comment by xqchiyyy** [comment]
试了一下，呼出toolbar以后确实可以呼出选项了！以前我一直用菜单栏上的点击选择来标注，这种方式是无法呼出的。再次感谢您！I Love Sketch Measure so much 👍

**Comment by utom** [comment]
或者快捷键多按一个 option
