### ISSUE TITLE
Toolbar doesn't respond

### ISSUE THREAD

**Issue by iamfrntdv** [utom/sketch-measure#188]
After using for a while toolbar stops responding. Only after reopening sketch helps but again just for a while

**Comment by utom** [comment]
mac OS version? and Sketch Measure version?

**Comment by iamfrntdv** [comment]
mac OS El Capitan 10.11.6
Sketch Measure 2.1 beta 2

**Comment by utom** [comment]
Let me check~

**Comment by iamfrntdv** [comment]
it seems like this appears with multiple sketch windows.. i tried to reproduce it once more but i couldn't.

**Comment by utom** [comment]
Im checking... thank you so much for your feedback.

**Comment by iamfrntdv** [comment]
thank you for such a great plugin!
