### ISSUE TITLE
Opening html shows only one artboard

### ISSUE THREAD

**Issue by Triguld** [utom/sketch-measure#189]
Hey, 

Im new to Sketch Measure, so maybe I'm doing it wrong. 

When I use 'Spec export' on a 'Page' with 3 'Artboards' in it and I open the .html file I only get to see 1 preview of an artboard. The content or colors don't even change when I select a different artboard. What does work is that it shows the measurements, colors and fonts of the different artboards, but it has no use when I can only see 1 preview for all 3 of them.

OS X 10.10.5
Sketch Version 39.1 (31720)

My english is not my native language, so I hope you guys can understand what I wrote.

Thanks in advance.

Greetings.
T

**Comment by utom** [comment]
Update last version, Export and uncheck "Advanced mode".
