### ISSUE TITLE
Use pixels for Line Height

### ISSUE THREAD

**Issue by jaminroe** [utom/sketch-measure#19]
Was wondering why the current Line property comes up as a percentage? Think it would be better to have it display pixels, especially for CSS purposes.

What do you think?

**Comment by formspiel** [comment]
No. Defiantly not.
Especially for modern CSS you’ll need the unit-less value (it’s percent). Pixels are dead ;-)
Even the font size should be rem (based on 16px base font size—mostly standard).

h1
  font-family: $font-1
  font-size: 2rem
  line-hight: 1.2

**Comment by redmondo** [comment]
I agree that more modern CSS practice uses %, em's and rem's, but some projects use pixels because of legacy code.

Forward thinking is definitely important, but it also doesn't allow for existing codebases that clients might already be using.

**Comment by MiMaMuh** [comment]
Hi, how could I generate a line-heigth label at all? Currently if i use the Get Typography tool it don't write any lh - do I have to use a special setting?

**Comment by redmondo** [comment]
@MiMaMuh Looks like the new version removes line height from the "get typography"  feature.

**Comment by utom** [comment]
"get typography" feature merged into the "get property", and using "sp", "pt" and "px"
