### ISSUE TITLE
Bug: Shortcuts bring up old settings panel, don't execute

### ISSUE THREAD

**Issue by byseeing** [utom/sketch-measure#190]
Typing a shortcut will only bring up the old settings panel again and again. They don't execute their functions. By contrast, navigating to a command through the menu bar works just fine, bringing up the new interface.

**Comment by byseeing** [comment]
I'm using Sketch Version 39.1 (31720)

**Comment by byseeing** [comment]
After uninstalling and reinstalling the plugin, the thumbs up icon is gone from the menu bar item, and no commands work. Navigating to a command or calling it via keyboard shortcut results in the old settings panel.

**Comment by byseeing** [comment]
Update: After a series or deleting, re-downloading and use attempts, I seem to have the latest version, which works.

I was using Sketch Toolbox a couple times to uninstall and reinstall, to no avail. Maybe look into that?

**Comment by utom** [comment]
Thank you for your feedback.
I'm not sure what is the problem about the Sketch Toolbox? I think you should be installed two versions of the Sketch Measure. You can check `Plugins` -> `Manage Plugins`, remove all version about `Measure` plugins, and download new version from the Github.
