### ISSUE TITLE
[Feature Request] Spec Export - order artboards according to order in sketch file - NOT alphabetically

### ISSUE THREAD

**Issue by golauree** [utom/sketch-measure#193]
On the spec export, can you build a feature or setting to order the artboards on the export based on the order of the artboards in the Sketch file.  Currently, the artboards are listed alphabetically in the spec export.   This isn't great.  Thanks!!!

**Comment by utom** [comment]
Thanks for your feedback, I remove alphabetically and keep order base.

**Comment by utom** [comment]
next version will be support choose order by

**Comment by utom** [comment]
![order artboards](https://cloud.githubusercontent.com/assets/761468/18613917/b5fa1082-7db6-11e6-833f-9a57e0ec0bb3.gif)
