### ISSUE TITLE
Spec exports not working on Sierra

### ISSUE THREAD

**Issue by florianpnn** [utom/sketch-measure#196]
Hi there,
I encountered a bug with the Spec exports, which doesn't work, on Sierra. I succeeded to take a screenshot of the visual glitch I can see instead of the plugin working.

![screen shot 2016-09-12 at 11 28 52](https://cloud.githubusercontent.com/assets/2725387/18431238/6766831c-78dc-11e6-9113-63d33eb751d4.png)

And here is the matching log :
`(Sketch Plugin)[14972]: TypeError: container.children is not a function. (In 'container.children()', 'container.children' is undefined)`

**Comment by utom** [comment]
Hello, @florianpnn 
Thank you for your feedback, can you tell me your Sketch Measure version?

**Comment by florianpnn** [comment]
I tried both the latest commit of master and 2.2, both give me the same result.

**Comment by utom** [comment]
Sorry, I have not upgraded my macOS, waiting for upgrade my macOS and check the bugs.

BTW, 2.2 is not final version, and I'm not sure the version is working well.

**Comment by utom** [comment]
@florianpnn  hello, try last version. Maybe is working.

**Comment by florianpnn** [comment]
It's now working, thanks for the quick support!
