### ISSUE TITLE
Changing DP/PT measurement in top menu works in reverse

### ISSUE THREAD

**Issue by iamaaronmartin** [utom/sketch-measure#198]
Built an Android file at MDPI size, and set that in the Export settings. After exporting, changing the measurement in the top right menu of the export HTML you get sizes in reverse.

Example: header measures 360dp wide at MDPI, but changing the measurements to XXXHDPI says the header is 90dp wide instead of 1440dp.

Looks like it's dividing instead of multiplying.

**Comment by utom** [comment]
If design is 360dp wide at XXXHDPI, so the design real pixel wide is 1440px, is not 1440dp.
(1440px = 360dp * XXXHDPI)
https://developer.android.com/guide/practices/screens_support.html
