### ISSUE TITLE
Smart Symbols + Export

### ISSUE THREAD

**Issue by halol** [utom/sketch-measure#199]
Hey, when you resize symbols. let's say: original is 200x200, but you set the properties with Resize Object, Pin to corner etc and then resize it to 200x400, export keep the original object values of 200x200. 
<img width="119" alt="screen shot 2016-09-14 at 14 12 09" src="https://cloud.githubusercontent.com/assets/2233348/18513413/49ff1c4e-7a85-11e6-88a3-fe2cefb81988.png">
<img width="201" alt="screen shot 2016-09-14 at 14 11 50" src="https://cloud.githubusercontent.com/assets/2233348/18513418/50486830-7a85-11e6-8707-08be48fb6e53.png">

**Comment by utom** [comment]
Can you tell me the Sketch Measure's version?

**Comment by utom** [comment]
Sketch v40 will fix it.
