### ISSUE TITLE
Create the object as union group

### ISSUE THREAD

**Issue by tobiastom** [utom/sketch-measure#2]
It would be awesome if you could create the "UI" elements in one union group. With that I could link this one object to a linked style and change all at the same time.

Hope the screenshots makes it clear.

Your arrangement:
![bildschirmfoto 2014-04-03 um 15 01 58](https://cloud.githubusercontent.com/assets/49210/2603531/360715a0-bb30-11e3-9ff8-c4c09b0ae0d6.png)

My wish:
![bildschirmfoto 2014-04-03 um 15 01 48](https://cloud.githubusercontent.com/assets/49210/2603533/3d76f6ca-bb30-11e3-88ba-8a942238c9c7.png)

**Comment by giuseppebergman** [comment]
Not for me: sometimes you need to add or delete something in the label. A union group would only make it harder to do, while not adding any advantage.
