### ISSUE TITLE
Please Add Speck Export select all 增加选择这个画板的选项

### ISSUE THREAD

**Issue by Luke699** [utom/sketch-measure#202]
建议新版本插件增加选择整个画板的选项

![export_choseall](https://cloud.githubusercontent.com/assets/21170310/18830875/4dbf47ca-8415-11e6-8327-aa28e1e730a1.png)

**Comment by utom** [comment]
左下角不是有吗?

**Comment by utom** [comment]
而且你这个是 2.0 版本, 现在 2.2 了~
