### ISSUE TITLE
Downolad assets function in exportable panel and slice tab

### ISSUE THREAD

**Issue by cypmal** [utom/sketch-measure#203]
Please add function that can allow user to download assets in export webview:
- In exportable panel (when u select icon/graphic) there should be button download all
- In slice tab where you have all assets from the artboard - there should be also button to download all

Because if you exporting for iOS/Android you have a lot of different sizes and it's hard to download each of them or even search them in the assets folder.
<img width="286" alt="zrzut ekranu 2016-09-30 o 10 42 13" src="https://cloud.githubusercontent.com/assets/22215227/18986232/4a2977d6-86fc-11e6-8558-f19d187488fd.png">

**Comment by utom** [comment]
Because the browser's security policy, can not do this function.
