### ISSUE TITLE
REM and spacing = rounded values

### ISSUE THREAD

**Issue by DarKDinDoN** [utom/sketch-measure#209]
Hello,

It seems that the spacing parameter (letter-spacing) is rounded.

Here is an example :

![capture d ecran 2016-10-16 a 20 54 22](https://cloud.githubusercontent.com/assets/1687854/19420045/a0748f24-93e3-11e6-95ad-011d1a40f5d4.png)

![capture d ecran 2016-10-16 a 20 53 41](https://cloud.githubusercontent.com/assets/1687854/19420048/a43890ec-93e3-11e6-9885-d4a251df3bae.png)

![capture d ecran 2016-10-16 a 20 56 31](https://cloud.githubusercontent.com/assets/1687854/19420050/ac3a5e9c-93e3-11e6-9336-94533a02be88.png)

Thanks

**Comment by utom** [comment]
fixed
