### ISSUE TITLE
导致Sketch 40.3 奔溃

### ISSUE THREAD

**Issue by evolutionjay** [utom/sketch-measure#214]
经过排查，是 sketch-measure 2.0.3 之后的版本导致 Sketch 40.3 奔溃。
`不包括2.0.3`

- 系统是 10.12.1
- 机器是 2015MBPR
- 排除性能/系统问题。

**Comment by utom** [comment]
现在都 2.2.1 了~!

**Comment by utom** [comment]
更新最新重启一下 Sketch!

**Comment by evolutionjay** [comment]
我就是用新的插件，挂了，我才回退到2.0.3

**Comment by utom** [comment]
怎么挂???

**Comment by utom** [comment]
10.12.1 没发布吧?

**Comment by utom** [comment]
已经检查过~ 插件没有问题
