### ISSUE TITLE
DP/SP mode and exporting assets

### ISSUE THREAD

**Issue by halol** [utom/sketch-measure#216]
Hey, I found this in the code:

`var androidDensity = {
            "@0.75x": "ldpi",
            "@1x": "mdpi",
            "@1.5x": "hdpi",
            "@2x": "xhdpi",
            "@3x": "xxhdpi",
            "@4x": "xxxhdpi"
        }`

and I noticed one weird thing: 
![screen shot 2016-11-01 at 11 16 17](https://cloud.githubusercontent.com/assets/2233348/19888169/d9647626-a024-11e6-8550-80d786bd009e.jpg)

but when I set all the sizes for Android (in the Export panel), I'll get every size I need.
I usually make them all trough the Sketch Export Assets > I get mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi by default). So just wondering if it's a good practice to export all of the sizes by default (e.g. set the export > 1x) and generate all android sizes by default.

Setting this for every asset is a bit frustrating (even when selecting multiple :) )
![screen shot 2016-11-01 at 11 23 58](https://cloud.githubusercontent.com/assets/2233348/19888300/b5905a20-a025-11e6-81db-490d528f12aa.jpg)

But maybe I'm wrong and just have wrong practice with exporting Android assets :)
Thanks!

**Comment by Greghster** [comment]
Yeah and it only exports either iOS or android assets, not both. It should give a panel option like slicer does. iOS should only go up to@3x by the way

**Comment by halol** [comment]
No, I'm just saying that instead of setting up the 1x, 1.5x, 2x, 3x, 4x for each time for every asset, it should export all the sizes when the project mode is set to Android (so you just to need to set only 1x in Export)

**Comment by Greghster** [comment]
I agree

**Comment by utom** [comment]
add it~
