### ISSUE TITLE
Emoji causes Spec export to fail

### ISSUE THREAD

**Issue by chrisplowman** [utom/sketch-measure#222]
Had issues with Spec Export where it wouldn't complete. I'd get some assets and pages but never the index.html file.

Worked out eventually that emojis in the design were causing it to fail, once they were deleted it worked perfectly.

**Comment by Schaertl** [comment]
A few of us are having similar issues on Sketch version 41, measure 2.3. On Spec Export we are getting a folder directory and asset folder with a background image, but no other folders or index.html page. We're not using emoji. Some are not even getting a directory structure. Tried detaching symbols, nothing.

**Comment by utom** [comment]
fixed v2.3.1
