### ISSUE TITLE
Broken in Sketch 41

### ISSUE THREAD

**Issue by girafic** [utom/sketch-measure#223]
«Plugin Output»
TypeError: color.hexValue is not a function. (In 'color.hexValue()', 'color.hexValue' is undefined)
line: 284
sourceURL: /Users/sbook/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript
column: 79

**Comment by utom** [comment]
Update to lastest version~

**Comment by brene** [comment]
I have the latest release version and it is still an issue. I have version 2.2.2. I think you have to create a release version to make it work with most plugin managers. To pull directly from master is not a good practice, right?
