### ISSUE TITLE
Spec Export.  no assets exported

### ISSUE THREAD

**Issue by Schaertl** [utom/sketch-measure#224]
A few of us are having similar issues on Sketch version 41, measure 2.3. On Spec Export we are getting a folder directory and asset folder with a background image, but no other folders or index.html page. We're not using emoji. Some are not even getting a directory structure. Tried detaching all symbols, nothing.

**Comment by Schaertl** [comment]
I reverted back to Sketch 40.3 and the measure spec export works.
http://www.sketchapp.com/download/sketch-40.3.zip

**Comment by utom** [comment]
fixed v2.3.1
