### ISSUE TITLE
html export broken in latest sketch release.

### ISSUE THREAD

**Issue by kdrift78** [utom/sketch-measure#225]
Having an issue exporting specs/redlines via the export assets function. I am on the latest build of measure and release of sketch.

**Comment by qmarcos** [comment]
Me too, when I'm exporting and selected the output folder, nothing happens... the export process seems to do its job, but no folder is created.

It happens since updating sketch to Version 41 (35326), this afternoon.

**Comment by stevenrkn** [comment]
Plus 1.

**Comment by jesseshowalter** [comment]
Having the same issue here as well

**Comment by pulpy** [comment]
same here.

**Comment by alensunny** [comment]
Please fix this. Unable to export the spec :(

**Comment by utom** [comment]
fixed v2.3.1
