### ISSUE TITLE
Export spec doesn't work on Sketch 41 update

### ISSUE THREAD

**Issue by kenemorales** [utom/sketch-measure#229]
Tried using sketch measure this morning but apparently the spec export functionality doesn't work with the new update. Had to rollback to sketch 40. Will really appreciate if guys can look into it please.

**Edit:** Fixed by upgrading to v2.3.1. Thanks utom!

**Comment by badyqb** [comment]
Same case here. Tried, nothing comes out after export

**Comment by CySchneider** [comment]
Here too. It calculates the output but no saving.

**Comment by adamex09** [comment]
I have similar issue: separate html files are generated (along the pngs) for each artboard, but no index.html (I have Advanced checked in).

Sketch 41 (35326)
Measure 2.3.1
El Captain 10.11.6 (15G1108)

**Comment by Pascal-fe** [comment]
It works on Sketch 41 but there is a bug with the zoom level. Some parts of the artboard are getting invisible when zooming-in/out. This only appears for the artboard with an important Height.

**Comment by dimitrieh** [comment]
got the same issue here

**Comment by utom** [comment]
Yep, update the plugin to v2.3.1, and you need restart the Sketch.

**Comment by kuswanto** [comment]
@utom, I am on Sketch v41 with plugin v2.3.3, the Spec Export isn't working.

**Comment by utom** [comment]
@kuswanto Maybe you restart Sketch, and now it works!

**Comment by tannerhuynh** [comment]
@utom The notes feature works, but is weird. Seems to create a container that isn't big enough for the notes inside of sketch. Otherwise it exports fine. More of an aesthetic issue.

**Comment by qmarcos** [comment]
Same here.

Sketch version 41 (35326) and latest version of the plugin. 
In some situations (not always, it seems to depend of some content of the artboards to export) no folder generated, separated html files by artboard generated... no html generated...

**Comment by kuswanto** [comment]
@utom I have restarted Sketch, reinstall the plugin. Still no generated folders. I will try do more experiment with different files to see if it's global or only on some specific files.

**Comment by swidnikk** [comment]
Works on some of my artboard and not others.... I tried to detach all my symbols (which have nested symbols and detached those too). Finally it started working...
