### ISSUE TITLE
Bug: The export of nested symbols does not work

### ISSUE THREAD

**Issue by cilurzo** [utom/sketch-measure#232]
The export does not work when I use nested symbols.

**Comment by swidnikk** [comment]
I have this problem too and verified this by detaching all of my symbols. Love the export functionality!

**Comment by dustinweeres** [comment]
Yea can verify. It used to work with nested symbols but now it doesn't. The export is so awesome and I use it daily!

**Comment by swidnikk** [comment]
@dustinweeres likewise I haven't seen a spec export as awesome as this in any of the design tools I've used. developers love it =)

**Comment by ryanbelisle** [comment]
I can verify as well. The progress indicator goes to 100% but the index.html file doesn't get created nor most of my artboards.

**Comment by utom** [comment]
fixed!
