### ISSUE TITLE
Bug v2.3.4: Nested Symbol Error - "Error: undefined" Dialog Shows on Export of Artboard with Nested Symbols

### ISSUE THREAD

**Issue by swidnikk** [utom/sketch-measure#238]
With the very latest update today, I get an export error, see screen shots below. Thank you! I love this plugin =)

![screen shot 2016-11-18 at 12 26 38](https://cloud.githubusercontent.com/assets/275252/20445557/6996fe2c-ad8a-11e6-96b9-1b03cfba5b79.png)

![screen shot 2016-11-18 at 12 26 49](https://cloud.githubusercontent.com/assets/275252/20445556/69968186-ad8a-11e6-907d-7b007b28c693.png)

**Comment by swidnikk** [comment]
Attached is a zipped up sketch file with an artboard to reproduce this error. Thanks for looking!

[Issue238Error.sketch.zip](https://github.com/utom/sketch-measure/files/600888/Issue238Error.sketch.zip)

**Comment by swidnikk** [comment]
More debugging... when the error is displayed, the symbol that throws the error shows up in my artboard. I simplified and can consistently reproduce with the file below. This appears to be an issue with nested symbols

![image](https://cloud.githubusercontent.com/assets/275252/20447412/86b8e228-ad93-11e6-9ba8-2c492a61f347.png)

[Issue238-SimpleReproduction.sketch.zip](https://github.com/utom/sketch-measure/files/600999/Issue238-SimpleReproduction.sketch.zip)

**Comment by ryanbelisle** [comment]
I'm getting the same issue but **it's not ALL Nested Symbol instances**. 

What I'm finding after the error is a duplicated, detached instance of the symbol. If I removed the original symbol and the detached instance and then insert a new version of the symbol, it will then export correctly.

**Comment by swidnikk** [comment]
@ryanbelisle yes I noticed the detached symbol too.... hmm... 

Okay, I tried your suggested workaround in the file [Issue238-SimpleReproduction.sketch.zip](https://github.com/utom/sketch-measure/files/600999/Issue238-SimpleReproduction.sketch.zip) and was able to export successfully. 

Next I scaled the new symbol instance, then added overrides. The failures happened again. 

![image](https://cloud.githubusercontent.com/assets/275252/20450762/cb8c3882-ada7-11e6-9015-b2d3e038d51f.png)

**Comment by utom** [comment]
Let me check~

**Comment by swidnikk** [comment]
Thank you!

**Comment by ryanbelisle** [comment]
Thanks @utom! You just made my day!
