### ISSUE TITLE
输出错误提示弹窗，何意？

### ISSUE THREAD

**Issue by YolandaKim** [utom/sketch-measure#239]
<img width="304" alt="qq20161121-0 2x" src="https://cloud.githubusercontent.com/assets/20694736/20471559/d26d5dd2-afed-11e6-9b38-ce7c5995c8f6.png">
这是什么意思？

**Comment by orpedocwong** [comment]
i got this too

**Comment by orpedocwong** [comment]
我解决了
- 我是关闭了自动保存的
- 我删除了 Symbols
- 可以正常导出了！
- 退出 Sketch ，不保存
- 再次打开，导出正常啦

- 谨慎尝试，做好备份
