### ISSUE TITLE
Spec Export not working

### ISSUE THREAD

**Issue by florianpnn** [utom/sketch-measure#240]
The spec export function is not working. the UI shows a completion but the folder is not created.

Here's the log error
```
Nov 21 12:15:16 Sketch[50330]: Exception: TypeError: color.hexValue is not a function. (In 'color.hexValue()', 'color.hexValue' is undefined)
Nov 21 12:15:16 Sketch[50330]: Info: {
	    column = 79;
	    line = 284;
	    sourceURL = "/Users/xxx/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript";
	}
Nov 21 12:15:16 Spec Export (Sketch Plugin)[50330]: TypeError: color.hexValue is not a function. (In 'color.hexValue()', 'color.hexValue' is undefined)
	line: 284
	sourceURL: /Users/xxx/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Measure.sketchplugin/Contents/Sketch/mark.sketchscript
	column: 79
```

**Comment by iamtimm** [comment]
I actually get an error message. I'm running `Version 41.1 (35376)` of Sketch.

![screen shot 2016-11-21 at 12 11 45 pm](https://cloud.githubusercontent.com/assets/2601332/20482280/c043c9f2-afe3-11e6-9702-f04bc30eb423.png)

**Comment by utom** [comment]
v2.3.43 now, update the plugin and restart sketch.app to try it newest.

**Comment by addflash77** [comment]
Works perfect !!! Thanks a lot!

**Comment by iamtimm** [comment]
@utom I updated but I still get the same error, just later in the process.

**Comment by utom** [comment]
@iamtimm if you restarted sketch.app and still get the same error, please sent me the document file, let me check~

**Comment by marvinhagemeister** [comment]
@florianpnn I'm curious: Where can one see the log output?

**Comment by florianpnn** [comment]
Working for me 👍 

@marvinhagemeister it's coming from the console.app
