### ISSUE TITLE
Export fails when Symbol overrides are set to `None`

### ISSUE THREAD

**Issue by marvinhagemeister** [utom/sketch-measure#241]
The error message:

`[__NSCFBoolean symbolID]: unrecognized selector sent to instance`

I'm unsure how to debug further at this point since I can't find a proper debug console

**Comment by swidnikk** [comment]
Hi! Thanks for fixing the other issue previously. I'm having this issue too =(

Steps to Reproduce
!. Create Symbol Instance
2. Override symbol text 
3. Export ---> Error :(
4. Clear override symbol text
5. Export ---> Error :(

Here is a video recording of reproducing this error
https://lookback.io/watch/dfaZpXE5xwdmXxeek

Here is zipped up sketch file that was used in the above video to reproduce this error,
[BugReport.sketch.zip](https://github.com/utom/sketch-measure/files/608162/BugReport.sketch.zip)

Thank you for helping keep Sketch Measure up to date!

**Comment by iamtimm** [comment]
Just found this too 👍

**Comment by utom** [comment]
@marvinhagemeister I need to know your plugin version and sketch version. if your all of latest version, could you sent the sketch document file let me check?

**Comment by utom** [comment]
@swidnikk let me check~

**Comment by iamtimm** [comment]
Here is a demo showing the problem 

[Sketch Measure Export Demo.zip](https://github.com/utom/sketch-measure/files/609291/Sketch.Measure.Export.Demo.zip)

**Comment by utom** [comment]
Sketch Measure has been updated to v2.3.44, I’m so sorry for that.

**Comment by marvinhagemeister** [comment]
@utom here is a minimal sample file, where the issue can be easily reproduced.

1. Open File
2. Select `02_Layouts` page
3. Export the `Export Me` layer with sketch measure

[measure_bug.sketch.zip](https://github.com/utom/sketch-measure/files/609494/measure_bug.sketch.zip)

**Comment by utom** [comment]
@marvinhagemeister I just test the file, that is working~ You can try to restart the sketch app and re-try.
