### ISSUE TITLE
Notes: <br> Tag does not work in Viewer 

### ISSUE THREAD

**Issue by HendrikVdB** [utom/sketch-measure#244]
If you create a note and using a paragraph for e.g.:

> Title
> Detail explanation of note

the generated Note in the Viewer will look like:

> Title `<br>` Detail explanation of note

![image](https://cloud.githubusercontent.com/assets/17026488/20633498/84743d00-b347-11e6-8a42-997d80963fa5.png)

Sketch 41 (35326) + Sketch Measure 25. Nov 2016

**Comment by utom** [comment]
Thank you for feedback, I will fix it~
