### ISSUE TITLE
ERROR:textLayer.stringValue is undefined !!!!!

### ISSUE THREAD

**Issue by manihome** [utom/sketch-measure#248]
<img width="304" alt="wx20161212-113827 2x" src="https://cloud.githubusercontent.com/assets/3824787/21087313/b0082858-c05f-11e6-8f68-05fff19cf9e2.png">

**Comment by utom** [comment]
看一下 Sketch.app 和 Sketch Measure, 是不是最新版本. 如果是最新版本, 请把出问题的文件发我看看.

**Comment by manihome** [comment]
【已解决】
我发现问题所在了，是用旧版本的Measure时添加过的#NOTE#，然后升级了插件，重新导出的时候图层的名字可能不被识别，我清除掉这些#NOTE#就可以正常导出了。
通过插件最新版本添加的#NOTE#就没有这个问题。
