### ISSUE TITLE
急！关于Measure2.4版本更新的问题

### ISSUE THREAD

**Issue by chenwangyao1990** [utom/sketch-measure#253]
最新版的sketch4.1.2和Measure2.4更新后。在工作时候通过画板导出切图标注包时候，会出现切图文件夹中都只有一倍图的bug（画板里的图层都设置了不同倍数的输出设置）。回家同样尝试一下（换台电脑），居然有些情况导出的是空的文件夹。这个问题困扰了我很久，希望大神能帮我解决这个问题，项目很赶...即使我卸了最新版换成之前的版本（3.3   3.5）依然是同样的问题,还是我设置有误，希望大神能给我回复。

**Comment by chenwangyao1990** [comment]
说错了 是2.4之前的版本都尝试了下

**Comment by utom** [comment]
重新安装后, 重启 Sketch 是非常有必要的~ 然后你也应该检查一下你的 Measure 的设置!

**Comment by chenwangyao1990** [comment]
mesaure我之前都是默认输出就好了  这版本需要特别设置吗 大神能否说仔细一点》。。

**Comment by utom** [comment]
1. 如果恢复到旧版, 重启一下 Sketch 才生效;
2. 如果你用新版注意一下设置的设备是 ios 还是 android;

**Comment by chenwangyao1990** [comment]
第二点能否说仔细点，不明白。。。

**Comment by utom** [comment]
新版导出有修改, 只要配置设定成了 ios 或者 android 设备, 会自动导出切片倍率切图
![screen shot 2017-01-04 at 1 08 20 am](https://cloud.githubusercontent.com/assets/761468/21615930/82023a62-d21a-11e6-9944-5b3e797df844.png)
![group 4](https://cloud.githubusercontent.com/assets/761468/21615935/8b016ab6-d21a-11e6-9baa-0423bf424b30.png)


但是正如你所说的如果有人选用"常规"的的确会导致只有一倍的设置 <- bug!

**Comment by chenwangyao1990** [comment]
有时候导出还是空的。。。有导出进度条 ，完了并没有生成

**Comment by utom** [comment]
你安装任何版本插件之后有没有重启 Sketch?

**Comment by utom** [comment]
你说的空白是切图空白? 还是标注空白?

**Comment by chenwangyao1990** [comment]
关了dock退出,　之前我都是用红宝石装卸载的

**Comment by chenwangyao1990** [comment]
是导出后进度条显示，显示完成后，相应路径并没有相应的文件夹生成（切图文件夹 总链接网页 子网页 效果图）都没有

**Comment by utom** [comment]
红宝石? SketchToolbox?
建议直接下载, 然后双击安装, 并重启 Sketch.
如果还是有问题, 建议把文件发给我看看.
