### ISSUE TITLE
Doesn't work with Sketch 42 (36781)

### ISSUE THREAD

**Issue by yareckk** [utom/sketch-measure#263]
Awesome time-saving plugin, but doesn't work after Sketch update to  v. 42.

**Comment by danmaitland** [comment]
Same here. Stpped working after update to v. 42

**Comment by utom** [comment]
im fixing~

**Comment by AshwinK** [comment]
Awesome, thanks! I can still hide/show existing elements I've added (i.e. overlay, spacing, properties). Just can't add new stuff. I'm a Product Designer at Mint. SERIOUSLY LOVE your stuff, can't wait to continue using in 42. This is a big part of my deliverables process

**Comment by utom** [comment]
just fixed!

**Comment by yareckk** [comment]
thank you @utom !

**Comment by danmaitland** [comment]
Thank you so much @utom !
