### ISSUE TITLE
同一个文本图层使用两种字体的时候，标注有误

### ISSUE THREAD

**Issue by iamlupeng1991** [utom/sketch-measure#274]
软件版本 42
插件：2.4.2

很惊喜的发现，同一个文本图层做两种字体的时候，导出的html文件中，能够智能识别两种字体的参数；不过随之也发现了问题，测试了之后发现，文字颜色为#000000的时候没问题，但是如果是其他颜色，则会出现其中一种字体颜色标注出错的情况。

详情可见附件。
最后感谢作者的出色工作。
[例子.zip](https://github.com/utom/sketch-measure/files/792181/default.zip)

**Comment by utom** [comment]
你最好检查一下你的 text view 是不是有选中改变颜色
