### ISSUE TITLE
切片问题

### ISSUE THREAD

**Issue by Ashung** [utom/sketch-measure#275]
Sketch Measure.sketchplugin/Contents/Sketch/library/common.js

Line: 2348

```javascript
layer.addLayers([sliceCopy]);
```

改为

```javascript
layer.insertLayers_beforeLayer([sliceCopy], layer.firstLayer());
```

**Comment by Ashung** [comment]
Line: 2346 这段都可以改成这样。已测试可用。

```javascript
if(this.is(layer, MSLayerGroup)){
    slice.moveToLayer_beforeLayer(layer, layer.firstLayer());
    slice.exportOptions().setLayerOptions(2);
}
```

建议增加切片按钮默认行为是增加切片图层。

**Comment by Ashung** [comment]
`MSSliceLayer.sliceLayerFromLayer(layer)` 是从图层的内容区创建切片，如果组内有一个区域大于图层内容的无填充边界图层。目前的增加切片功能不会包含边界图层区域。

如果用`MSSliceLayer.alloc().init()` 然后把图层的位置尺寸加到切片上，这样如果图层包括投影和边框，切片区是不包括投影和边框的。

所以需要把两种位置尺寸信息合并，作为新建切片的位置尺寸。

```javascript
if(layerRect.width > sliceRect.width){
    sliceRect.setX(layerRect.x);
    sliceRect.setWidth(layerRect.width);
}

if(layerRect.height > sliceRect.height){
    sliceRect.setY(layerRect.y);
    sliceRect.setHeight(layerRect.height);
}
```

这段代码在某些极端的情况下，切片不会包含所有内容。

用`MSRect.rectWithUnionOfRects`合并 `Rect`：

```javascript
var msRect = MSRect.rectWithUnionOfRects([
    MSRect.alloc().initWithRect(slice.absoluteRect().rect()),
    MSRect.alloc().initWithRect(layer.absoluteRect().rect())
]);

slice.absoluteRect().setRect(msRect.rect());
```

**Comment by utom** [comment]
已做修改, 非常感谢~ 有机会多多交流 wechat: utomvip

**Comment by Ashung** [comment]
https://github.com/utom/sketch-measure/blob/master/Sketch%20Measure.sketchplugin/Contents/Sketch/library/common.js#L2332-L2337

```
slice.absoluteRect().setRect(layer.absoluteInfluenceRect());
```

发现这个属性会包含无填充的图层。

**Comment by quweijia** [comment]
> 图层组的切片移动到最底层
> 
> 行：2346这段都可以改成这样。已测测可用。
> 
> ```js
> if（this。是（layer，MSLayerGroup））{
>      slice。moveToLayer_beforeLayer（层，层。firstLayer（））;
>     切片。exportOptions（）。setLayerOptions（2）;
> }
> ```
> 
> 建议增加切片按钮默认行为是增加切片图层。

如何将切片至于编组首层
