### ISSUE TITLE
Why is 16rem not a default option in Sketch Measure? 

### ISSUE THREAD

**Issue by levibostian** [utom/sketch-measure#278]
In a Sketch Measure export, I am able to change to Rem sizes over Px sizes. This is great, thank you!

![screen shot 2017-03-07 at 4 14 34 pm](https://cloud.githubusercontent.com/assets/2041082/23680546/3d959dde-0351-11e7-846a-a8ff8bf6afe1.png)

However, I am wondering why is 16rem not one of the default options? I understand that I can change via the Sketch Measure settings to use 16rem via a custom export type, however, why is it not a default option? 

I ask this because 16rem is the default with modern browsers today according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size)

<img width="649" alt="screen shot 2017-03-07 at 4 18 43 pm" src="https://cloud.githubusercontent.com/assets/2041082/23680706/cc81c8c4-0351-11e7-9f67-eb3a2addcca5.png">

Not a big deal, but wondering out of curiosity and not having to tell each designer I work with to create a custom export type for me. Having 16 as a default option would overcome that.

**Comment by utom** [comment]
thank you for the feedback~ I had add it :D
