### ISSUE TITLE
导出 HTML 文件，左侧没有缩略图

### ISSUE THREAD

**Issue by mayuyuyu** [utom/sketch-measure#302]
已取消选中「高级模式」。
生成的文件夹中仅包含每个画板生成的 HTML，文件夹中没有 links 和 preview 文件夹。
在其他人的电脑导出没问题，操作设置没差别，插件为目前最新版本。

**Comment by utom** [comment]
高级模式的确左侧没有缩略图的, 比较简单粗暴
