### ISSUE TITLE
Nested symbols not showing specs

### ISSUE THREAD

**Issue by leannegunn** [utom/sketch-measure#303]
When I export a file with symbol instances that have nested symbols, the specs do not show up for those nested symbols.

**Comment by thewinger** [comment]
+1 with this issue

**Comment by jamesmellers** [comment]
+1 with this too. Possibly related, I'm seeing strange behavior with overrides. When I run Spec Export, visually the overrides are showing correctly but when I mouseover/click them, it's as if symbol instances are showing their defaults, not the overrides.

**Comment by quitefrank** [comment]
+1 with this.

For me, it seems when I export a nested symbol with icon overrides for example, only the original instance of that symbol is exported. In other words, if I have a button with an icon as the template symbol and then use multiples of that button with different icons, only the icon within the symbols page is exported.
