### ISSUE TITLE
Sketch Measure broken in Sketch 45

### ISSUE THREAD

**Issue by matthbooth** [utom/sketch-measure#325]
Having an issue with latest Sketch Measure and Sketch version 45.
Just seeing a black Sketch Measure window.

Anyone else having this problem?

**Comment by jayliu50** [comment]
Yes. This?

![image](https://user-images.githubusercontent.com/673862/27763055-84e67e66-5e4a-11e7-9a92-abfb4144e4d9.png)

Seeing this in 44.1 and 45 beta.

**Comment by matthbooth** [comment]
That's what I am seeing too

Kind regards

MATT BOOTH
ILK.
+44 (0)7939 408 879

Website | Twitter | Instagram | BLAB

Ilk Studio Ltd is registered in England and Wales No. 6534940

© 2015. Ideas, designs, proposals & suggestions in this email belong to Ilk Studio Ltd. All rights reserved.

**Comment by jayliu50** [comment]
For me, I notice that this happens when I'm behind an http proxy. Leaving the proxy or turning off my internet connection and restarting Sketch will cause it to work fine.

I wonder if the plugin is trying to make http requests while it renders its interface...

**Comment by matthbooth** [comment]
Thanks I'll try that.
Such a useful plugin for me to be without.

Kind regards

MATT BOOTH
ILK.
+44 (0)7939 408 879

Website | Twitter | Instagram | BLAB

Ilk Studio Ltd is registered in England and Wales No. 6534940

© 2015. Ideas, designs, proposals & suggestions in this email belong to Ilk Studio Ltd. All rights reserved.

**Comment by utom** [comment]
Yep, I see that.  Any updates isn't working via the Sketch Updater. Try to download new version from web.
