### ISSUE TITLE
Unable to mark properties with Toolbar and Toolbar 2.0 (Beta) 

### ISSUE THREAD

**Issue by mrjeoffrey** [utom/sketch-measure#326]
Sketch Version 45 (43475)
Sketch Measure v2.6.4

Toolbar and Toolbar 2.0 (Beta) are visible. Mark functions work except for "properties". Attempted to Mark Properties from Toolbar, Toolbar 2.0 (Beta), and from the Plugin menu. Was not successful

Toolbar -> Tap Mark Properties -> No response
Toolbar 2.0 (Beta) -> Tap Label - Mark Properties (one of the 4 icons) -> Dialogue box opens up for property parameters -> #properties folder created but no properties shape and layers.
Plugin Menu -> Tap Mark Properties -> No response

:(

**Comment by silvinacouto** [comment]
Exact same issue with same versions. Can this be fixed ASAP please?

**Comment by utom** [comment]
I'm so sorry for that, new version fixed it

**Comment by silvinacouto** [comment]
Thanks!
