### ISSUE TITLE
There is some shadow with my svg files exported.

### ISSUE THREAD

**Issue by YihangFu** [utom/sketch-measure#328]
Though I didn't use shadow on these svg icons.
Is that a bug?

- Sketch Version 43
- Sketch measure Version 2.6.4

**Comment by utom** [comment]
Sketch measure Version 2.6.5 is fixed

**Comment by YihangFu** [comment]
感谢回复，我更新了 Sketch 和 Sketch Measure 到最新版，仍然存在问题，不知道出在哪里，还是决定先反馈一下。

问题如图：
<img width="516" alt="wx20170712-172124 2x" src="https://user-images.githubusercontent.com/19548176/28111144-11244d92-6727-11e7-939a-4c5f76b81190.png">

<img width="212" alt="wx20170712-172145 2x" src="https://user-images.githubusercontent.com/19548176/28111145-1124e090-6727-11e7-87db-120982994a44.png">

<img width="397" alt="wx20170712-172237 2x" src="https://user-images.githubusercontent.com/19548176/28111143-111f84f6-6727-11e7-88fc-d21dde677458.png">

**Comment by ignaty** [comment]
@YihangFu it seems as Sketch issue but were you able to solve that?

**Comment by agourdji** [comment]
Hi, I'm having the same issue, were you able to solve it?
