### ISSUE TITLE
能不能支持一键下载所有的切图素材

### ISSUE THREAD

**Issue by zhongerxin** [utom/sketch-measure#329]
因为为了方便协作，我们都是把导出后的文件放到服务器里，工程狮直接访问网址来切图，因此能一键下载切图素材就显得灰常重要了。
谢谢 作者大大了

**Comment by utom** [comment]
本来就放在本地, 有文件夹.

**Comment by rickytan** [comment]
我遇到了同样的问题，于是做了个插件：https://github.com/rickytan/sketch-measure-downloader
