### ISSUE TITLE
Restart Popup looks like a phishing attempt. 

### ISSUE THREAD

**Issue by benarent** [utom/sketch-measure#338]
With the recent update it required a restart, the donate link went to http://utom.design/measure/donate.html?ref=update but neither of these say that these donations are for Sketch Measure. I would suggest adding clearer instructions to the popup and landing page. That the donations is for Sketch Measure. 

<img width="508" alt="screen shot 2017-07-18 at 1 10 58 pm" src="https://user-images.githubusercontent.com/559288/28337625-0b07ef5c-6bbb-11e7-9495-c353b70ae99b.png">

**Comment by utom** [comment]
Click the "Restart the Sketch.app" button.
