### ISSUE TITLE
Can not use sketch measure

### ISSUE THREAD

**Issue by Seihui** [utom/sketch-measure#339]
Recently, I update my OS. And then, I can not use Sketch Measure any more. Whatever I click, there was no response, just like I have not click it.  I have tried to reinstall Sketch and Sketch Measure, it's useless. My OS version is High Sierra 10.13 beta and Sketch version is 45.2.，Sketch Beta 46 can't work.

**Comment by ZTfer** [comment]
同样不能用。。。

**Comment by pillowsk3** [comment]
I'm also running Sketch 45.2; Sketch Measure doesn't work.

**Comment by utom** [comment]
I uninstalled the plugin. Then redownloaded through sketch's plugin manager. Works now.

**Comment by Seihui** [comment]
I uninstalled it and install it, it does not work. Is that my OS's problem?
