### ISSUE TITLE
Include Text style Name as an option in Properties

### ISSUE THREAD

**Issue by rileyflorence** [utom/sketch-measure#34]
When working with Style guide it's often more useful for my developers when I just call out the style that's being used instead of defining the typeface, size, & color every time. I've built my template's styles and names to map perfectly to the CSS styles being used in the code so it would be a simple translation for them. I'd love to be able to select "Text Style" as one of the options under the properties window.

What do you think?

**Comment by gilboat** [comment]
Yes, this.

**Comment by arjenvr** [comment]
Being able to select the Text Style name in the Properties would be very useful.

**Comment by utom** [comment]
added
