### ISSUE TITLE
Sketch measure 2.6.8 and Sketch 45.2

### ISSUE THREAD

**Issue by StephZA** [utom/sketch-measure#342]
Hi, I have been having endless issues all f a sudden with this plugin (my absolute favorite and a must in my job).

It has stopped working and not matter how many things I have tried, I can't get it to work anymore. This is an issue for me a the spec export is SOOO important for my developers.

Please please help

**Comment by utom** [comment]
Update to v2.6.12

**Comment by StephZA** [comment]
Thanks
