### ISSUE TITLE
Automatically combine measurement objects into a single layer

### ISSUE THREAD

**Issue by redmondo** [utom/sketch-measure#35]
I find myself manually grouping all measurement elements into a single layer that I can turn on and off. 

It would be helpful if these elements were automatically put into a layer called something like "Specs" so their visibility can be easily controlled.

**Comment by gilboat** [comment]
You can toggle visibility with control-shift-H. Though I agree, it'd be nice to have these under one grouped layer for easier layer management.

**Comment by utom** [comment]
Try to new
