### ISSUE TITLE
Sketch Beta 3.3

### ISSUE THREAD

**Issue by mischugo** [utom/sketch-measure#36]
Is there any update comming for the Beta 3.3?

**Comment by josecruz** [comment]
++ for that :+1:

**Comment by basiclines** [comment]
+1

**Comment by jmdenis** [comment]
I really miss it too +1

**Comment by luloodesign** [comment]
+++ :+1:

**Comment by jiserra** [comment]
I'm leaving just a +1, I wish I knew how to fix this!

**Comment by alexcolbeck** [comment]
+++ :+1:

**Comment by vjandrei** [comment]
+++

**Comment by sambert** [comment]
I want access to the previous version. This latest one has the Spec Export, but the normal 'Properties' is not working well. It sometimes doesn't work at all. Also, the ability to select the location of the spec has been removed, not sure why.
