### ISSUE TITLE
Save color settings

### ISSUE THREAD

**Issue by herrhaase** [utom/sketch-measure#38]
Right now the color settings (style guide) reset for each time I restart Sketch. Would be great if those could be saved in the general settings of the plugin.

Thanks.

**Comment by badlydrawnrob** [comment]
Same goes for the design resolution settings, would be helpful if the plugin remembered user settings with an option to reset to defaults?

**Comment by herrhaase** [comment]
@utom Any update here? :)

**Comment by utom** [comment]
try new~

**Comment by herrhaase** [comment]
@utom Ok, there are a bunch of changes, yes - but I don't find the settings anymore, the text layer has now 2px character spacing and every time I use the plugin it creates a hidden config file in my artboard, which doesn't give me any control. 

Can you please check? The initial problem is still existing and now the tool is not usable anymore at all.
