### ISSUE TITLE
Error on Spec Export

### ISSUE THREAD

**Issue by nzmb** [utom/sketch-measure#400]
After begin exporting in few seconds open the folder with spec exported files.

The spec export popup frees on this status
![spec-exoprt](https://user-images.githubusercontent.com/4814617/36784580-fe087358-1c90-11e8-890f-2d714fddbf86.png)

But files just contain:
- `index.html` file
- `preview` folder
- `links` folder

And the export contains only with preview **.png** file.

Data:
Sketch Version 49 (51002)
Mac OS  Version 10.13.3 (17D102)
Plugin Version 2.7

**Comment by kacho** [comment]
Same issue after updating to Sketch 49. It was working fine yesterday on Sketch 48

**Comment by anne-abert** [comment]
+1

**Comment by jjaszkin** [comment]
Hey!
I have the same problem after updating Sketch to Version 49

**Comment by andreiinc** [comment]
+1

**Comment by xenqtron** [comment]
+1

**Comment by andrewbradypolymorph** [comment]
+1

**Comment by hornhollow** [comment]
+1

**Comment by stanleyfok** [comment]
+1

**Comment by andrewbradypolymorph** [comment]
Update today seems to have fixed it. 
:-)

**Comment by nzmb** [comment]
**Thanks for updates**
The updated version: `2.7.2` fixes the bug.
