### ISSUE TITLE
Spec Export does not work with Sketch 49

### ISSUE THREAD

**Issue by iamfederico** [utom/sketch-measure#402]
With the update of Sketch to version 49, Spec Export does not work. It will export the html file but when you look at Sketch, the export layers are stuck.

**Comment by mkinberg** [comment]
Same issue here.  I've also tried toggling 'Advanced Mode' and 'Export Layer Influence Rect' options with no success.

**Comment by AsheBaby** [comment]
Same issue here!

**Comment by syazanabtm** [comment]
I am experiencing the same issue

**Comment by ng524** [comment]
me too...😢

**Comment by subakk** [comment]
Plugin doesn't work properly.

**Comment by utom** [comment]
fixed~

**Comment by iamfederico** [comment]
Thanks @utom 
It works now!
We all appreciate

**Comment by elizaio** [comment]
@utom 
I'm using sketch v51.3 and export specs is freezing and doesn't progress. 
I've tried multiple files with no luck. 
Uninstalled Sketch Measure and reinstalled. No luck.
I've restarted.
Nothing is working.
Help?
Thanks!!!

![screen shot 2018-10-25 at 11 30 14 am](https://user-images.githubusercontent.com/15219093/47522031-65630300-d849-11e8-81bf-d26186895d57.png)

**Comment by melissasamworth** [comment]
@elizaio I'm having the same issue. Have also troubleshooted with all the same methods. @utom you are truly a saint for creating this plugin, thank you so freaking much. Also... could you help us? :)

**Comment by wendyhoneycutt** [comment]
I'm having the same problem. It took me a bit to realize it was hanging on a path. I tested it by deleting the first path on the layer where it got hung up, then it would hang again on the next path on the layer. Unfortunately, I can't delete all the paths in the sketch file in order to export the specs... please fix!

**Comment by elizaio** [comment]
I have a potential fix...
Updated to macOS High Sierra Version 10.13.6, the updated to Sketch 52.3.
Exporting specs for individual artboards now works but will still hang if I select multiple artboards.

FWIW, my company doesn't support Mojave yet so I'm hamstrung.

**Comment by Shafir** [comment]
on Sketch v 51.2
nothing seems to work, export stalls and never finish.
tried to reinstall with no success...:-( @
