### ISSUE TITLE
Sketch V49 Compatibility?

### ISSUE THREAD

**Issue by brandbrilliance** [utom/sketch-measure#403]
Does this have Sketch v49 compatibility. Don't want to upgrade until it does. Also, maybe you can post somewhere on the GitHub what the latest version of sketch is that is supported by each release (like a note).

**Comment by nzmb** [comment]
Duplicate with #400 fixed with update 2.7.2

**Comment by revelt** [comment]
Let's close this issue, plugin works fine on `v49.1`.

**Comment by luxlogica** [comment]
@utom It's likely that this issue can be safely closed now.
