### ISSUE TITLE
Plugin not working with latest update of Sketch (49)

### ISSUE THREAD

**Issue by clucius** [utom/sketch-measure#405]
I have the latest version of sketch measure (2.7.2) on my Mac but when sketch came out with the latest update this week to version 49, sketch measure stopped working. The specific problem I'm having is that the plugin is exporting a spec page that is just a solid image instead of marked up.

**Comment by mpr-outermedia** [comment]
I have the same problem since I yesterday updated to version 49. Please fix this asap :)

**Comment by mpr-outermedia** [comment]
It's been fixed, thanks! Installing the newest version works properly.
