### ISSUE TITLE
Default character space to 0

### ISSUE THREAD

**Issue by redmondo** [utom/sketch-measure#41]
Love the shared styles for the labels, but am always changing the character spacing from the default value of 2 to 0.

Would be easier if 0 was the default.

**Comment by plainclothes** [comment]
Fork it! Or just modify your local copy ;-)
Here's the line to search for in library/common.js (< did I remember that right?)
textLayer.setCharacterSpacing(2);

**Comment by utom** [comment]
fixed~

**Comment by redmondo** [comment]
thanks guys!!
