### ISSUE TITLE
Get Size crashing Sketch

### ISSUE THREAD

**Issue by ryanbelisle** [utom/sketch-measure#44]
Hi,
I was using Measure on a few Artboards just fine. For some reason now if I choose an object and GET SIZE, Sketch sits there, shows these black boxes over the screen, and then ultimately crashes.

I copied a few Artboards into a new Sketch file and it seems like 1 Artboard is causing the issues. If the Artboard is present in the file, it will crash Sketch. On that Artboard I deleted all the spec folders as well. It still crashes.

Thoughts?

**Comment by utom** [comment]
I got it. maybe you can check your all style shared, will find names is the same, delete one of them.

btw What is your version of mac os?

**Comment by ryanbelisle** [comment]
All style shared, what's that exactly?

Hmm, it's my work laptop. I believe it's 10.10.2 or 10.10.3

**Comment by utom** [comment]
<img width="406" alt="screen shot 2015-07-18 at 5 15 52 pm" src="https://cloud.githubusercontent.com/assets/761468/8761089/bb66b44a-2d70-11e5-9f20-b1f4dbec8b75.png">
find the same name, and delete it
