### ISSUE TITLE
Can't use "Spec Export" in sketch 52 beta

### ISSUE THREAD

**Issue by taichikume** [utom/sketch-measure#465]
Not react when press the Export button.

**Comment by totocasti** [comment]
same think in the official S52 release

**Comment by tonygray216** [comment]
same thing in release

**Comment by ohFRY** [comment]
same. So annoying :(

**Comment by johnblopez** [comment]
Doesn't work with Sketch 52/52.1
After reading previous "Measure doesn't work with latest Sketch update" it looks like we should ALWAYS expect that Measure will take some time to catch up with the most current Sketch update; that's just how it is, evidently.

**Comment by taichikume** [comment]
ellunium to fix it. Thank you very Much.
https://github.com/utom/sketch-measure/issues/468#issuecomment-427589418
