### ISSUE TITLE
Bug: Spec export

### ISSUE THREAD

**Issue by bedrmninja** [utom/sketch-measure#52]
Hi i'm glad that you guys are adding this function, very handy.

i understand this particular function is in beta, but thought i'd share a bug with you.

spec export function works fine but for some pages, it creates blank html documents.

i have tried to get rid of one elements at a time and re-exporting and found out that a type layer (paragraph, custom fonts) is causing the issue.

I have other custom fonts exporting ok so i'm not sure if the font is the issue?

Would be great if you guys could take a look at any bugs around font layer with spec export.

thanks for great work guys!

![screen shot 2015-08-04 at 10 36 02 am](https://cloud.githubusercontent.com/assets/13633483/9050729/ac0228dc-3a94-11e5-9ae6-d48e90e1b243.png)
![screen shot 2015-08-04 at 10 36 13 am](https://cloud.githubusercontent.com/assets/13633483/9050731/b3215a48-3a94-11e5-9284-503944e407dd.png)

**Comment by utom** [comment]
could you share the sketch document for me?

**Comment by bedrmninja** [comment]
i cant seem to attach a .sketch doc..

**Comment by bedrmninja** [comment]
https://www.dropbox.com/s/5cclyf681x0efcf/SketchMeasure_bug.sketch?dl=0

**Comment by utom** [comment]
@bedrmninja Working :D

**Comment by bedrmninja** [comment]
As in its working now???

**Comment by bedrmninja** [comment]
Thanks man@ Awesome!!!

**Comment by krnlde** [comment]
We found out that spec export is empty when the artboard contains a textfield with different paragraph formats. This is directly related to this issue, because we see the same exported and empty result. (Mac OSX 10.10.3, Sketch 3.3.3, sketch-measure latest)

**Comment by utom** [comment]
If you could share the .sketch file with me?

**Comment by krnlde** [comment]
Of course! Thank you for your fast response!
https://drive.google.com/folderview?id=0B_o9BHtQH2yENWI4aWN6Z19vX1U&usp=sharing
It looks like the exported file is still very big, so something should be inside, but the dimensions seem to be broken.

Again, thank you for your support

**Comment by utom** [comment]
fixed~

**Comment by krnlde** [comment]
What did you fix where?

**Comment by utom** [comment]
Are you sure your plugin is last version?

**Comment by krnlde** [comment]
Am I supposed to pull the plugin again? the master branch is edited 4 days ago. That's why I'm asking.

**Comment by utom** [comment]
@krnlde Im sure your export html is old, remove and pull last version

**Comment by krnlde** [comment]
I can confirm that with the newest version of sketch-measure the phenomenon disappeared. Thank you for your support :)
