### ISSUE TITLE
Bug: Spec Export - HEX not exporting.

### ISSUE THREAD

**Issue by bedrmninja** [utom/sketch-measure#53]
the blank document bug was fixed but now the hex value is not coming up on the right hand side.

![screen shot 2015-08-05 at 4 43 31 pm](https://cloud.githubusercontent.com/assets/13633483/9079791/3a6a5a84-3b91-11e5-90ef-2b15810a6b77.png)

**Comment by utom** [comment]
click color text to change color format.
