### ISSUE TITLE
Size and spacing issue

### ISSUE THREAD

**Issue by kbstellent** [utom/sketch-measure#542]
The size only displays width, and the spacing only displays vertical measure (if 1 layer is inside the other).

I'm using Sketch (53)

**Comment by clarewarburton** [comment]
II have same issue with Sketch 53

**Comment by idsampaio** [comment]
@kbstellent @clarewarburton https://github.com/utom/sketch-measure/issues/536

**Comment by kbstellent** [comment]
Fix here: [Issue 565](https://github.com/utom/sketch-measure/issues/565)
