### ISSUE TITLE
UX idea: Label Positioning dialog

### ISSUE THREAD

**Issue by blynkkk** [utom/sketch-measure#55]
Thanks for the great plugin. I use it almost every day - this is such a time-saver!
I noticed that I'm always using different positions for labels, especially for object "Properties". So I came up with an idea how to make the whole process 50% faster and save even more time: 

![label_positioning_idea4](https://cloud.githubusercontent.com/assets/11541426/9121514/b5abc68c-3c50-11e5-8fef-c6db1e991a11.png)

It would be great to implement it to every label positioning setting. What do you think?

**Comment by blynkkk** [comment]
Evolution of the idea :)

![label_positioning_idea3](https://cloud.githubusercontent.com/assets/11541426/9121432/395a9c52-3c50-11e5-903f-b1b1c82549af.png)

**Comment by giuseppebergman** [comment]
Excellent idea! I, too, waste a lot of time using that positioning drop-down menu.

**Comment by utom** [comment]
Last version update!
