### ISSUE TITLE
Sketch 53 导出的时候会在画板上复制同样的symbol实例，然后卡住

### ISSUE THREAD

**Issue by CloverTuan** [utom/sketch-measure#560]
如题

**Comment by ellunium** [comment]
@CloverTuan Please give this a try: [#536](https://github.com/utom/sketch-measure/issues/536#issuecomment-466636471)

**Comment by CloverTuan** [comment]
> @CloverTuan Please give this a try: [#536](https://github.com/utom/sketch-measure/issues/536#issuecomment-466636471)

Thanks for your reply. I have tried but it dosen't work.

**Comment by ellunium** [comment]
@CloverTuan Remember to **uninstall the plugin**, **restart sketch** and install the downloaded version, just to make sure there's **no cached plugin information**.

Also, make sure you're using **Sketch v53.2 (72643)**.

**[Download from sketch-measure-latest](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)**

# Still not working?
Follow the steps below:

- [ ] Uninstall the plugin
- [ ] Quit Sketch
- [ ] Follow the steps bellow to remove the `PluginsWarehouse` folder
- [ ] [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)
- [ ] Reinstall the plugin
- [ ] Test the `Mark Properties / Spec Export` again

> Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> - Go to the Finder of Mac OS
> - From the “Go” menu navigate down to “Go to Folder” or...
> - Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> - Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> - Remove/Delete the `PluginsWarehouse` folder

I hope it helps  :)

**Comment by CloverTuan** [comment]
> @CloverTuan Remember to **uninstall the plugin**, **restart sketch** and install the downloaded version, just to make sure there's **no cached plugin information**.
> 
> Also, make sure you're using **Sketch v53.2 (72643)**.
> 
> **[Download from sketch-measure-latest](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)**
> 
> # Still not working?
> Follow the steps below:
> 
> * [ ]  Uninstall the plugin
> * [ ]  Quit Sketch
> * [ ]  Follow the steps bellow to remove the `PluginsWarehouse` folder
> * [ ]  [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)
> * [ ]  Reinstall the plugin
> * [ ]  Test the `Mark Properties / Spec Export` again
> 
> > Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> > 
> > * Go to the Finder of Mac OS
> > * From the “Go” menu navigate down to “Go to Folder” or...
> > * Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> > * Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> > * Remove/Delete the `PluginsWarehouse` folder
> 
> I hope it helps :)

It works!! Thank you so much! 👍
