### ISSUE TITLE
Doesn't work mask after export in the Sketch 53.2 and Sketch-measure 2.7.9

### ISSUE THREAD

**Issue by LenaAlyanova** [utom/sketch-measure#569]
Hi
After updating  program and plugin  my frontend-guy can not see right color  by several elements. I used mask  for all thi elements.
<img width="840" alt="зображення" src="https://user-images.githubusercontent.com/43852315/54824604-1912d680-4cb4-11e9-84d4-fcc6038271d0.png">

If you need I can send you sketch.file and  zip.file ( files after export)

Please, fix this problem.

**Comment by ellunium** [comment]
@LenaAlyanova, please give this a try:

Remember to **uninstall the plugin**, **restart sketch** and install the downloaded version, just to make sure there's **no cached plugin information**.

Also, make sure you're using **Sketch v53.2 (72643)**.

### Get the Fork version (v2.8.0)
**[Download from sketch-measure-latest](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)**

# Still not working?
Follow the steps below:

- [ ] Uninstall the plugin
- [ ] Quit Sketch
- [ ] Follow the steps bellow to remove the `PluginsWarehouse` folder
- [ ] [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)
- [ ] Reinstall the plugin
- [ ] Test the `Mark Properties / Spec Export` again

> Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> - Go to the Finder of Mac OS
> - From the “Go” menu navigate down to “Go to Folder” or...
> - Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> - Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> - Remove/Delete the `PluginsWarehouse` folder

Let me know how it goes 😊

If after all this it still doesn't work, please share a small sketch example file (doesn't need to be your actual design file) that you can reproduce the bug and I'll take a look.

**Comment by LenaAlyanova** [comment]
Thank you very much. It works  )

**Comment by LenaAlyanova** [comment]
Thank you very much. It works  )
