### ISSUE TITLE
Sketch 53.1 只要包含 Symbol 就无法导出 Spec

### ISSUE THREAD

**Issue by TimWu0318** [utom/sketch-measure#571]
只要包含 Symbol 就无法导出 Spec，需要将其解除 Symbol 才能导出。

**Comment by ellunium** [comment]
@TimWu0318 , please give this a try:

Remember to **uninstall the plugin**, **restart sketch** and install the downloaded version, just to make sure there's **no cached plugin information**.

Also, make sure you're using **Sketch v53.2 (72643)**.

### Get the Fork version (v2.8.0)
**[Download from sketch-measure-latest](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)**

# Still not working?
Follow the steps below:

- [ ] Uninstall the plugin
- [ ] Quit Sketch
- [ ] Follow the steps bellow to remove the `PluginsWarehouse` folder
- [ ] [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)
- [ ] Reinstall the plugin
- [ ] Test the `Mark Properties / Spec Export` again

> Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> - Go to the Finder of Mac OS
> - From the “Go” menu navigate down to “Go to Folder” or...
> - Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> - Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> - Remove/Delete the `PluginsWarehouse` folder

Let me know how it goes 😊

If after all this it still doesn't work, please share a small sketch example file (doesn't need to be your actual design file) that you can reproduce the bug and I'll take a look.

**Comment by TimWu0318** [comment]
> @TimWu0318 , please give this a try:
> 
> Remember to **uninstall the plugin**, **restart sketch** and install the downloaded version, just to make sure there's **no cached plugin information**.
> 
> Also, make sure you're using **Sketch v53.2 (72643)**.
> 
> ### Get the Fork version (v2.8.0)
> **[Download from sketch-measure-latest](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)**
> 
> # Still not working?
> Follow the steps below:
> 
> * [ ]  Uninstall the plugin
> * [ ]  Quit Sketch
> * [ ]  Follow the steps bellow to remove the `PluginsWarehouse` folder
> * [ ]  [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)
> * [ ]  Reinstall the plugin
> * [ ]  Test the `Mark Properties / Spec Export` again
> 
> > Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> > 
> > * Go to the Finder of Mac OS
> > * From the “Go” menu navigate down to “Go to Folder” or...
> > * Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> > * Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> > * Remove/Delete the `PluginsWarehouse` folder
> 
> Let me know how it goes 😊
> 
> If after all this it still doesn't work, please share a small sketch example file (doesn't need to be your actual design file) that you can reproduce the bug and I'll take a look.

Thanks for your method, it works.👍👍
