### ISSUE TITLE
Spec Export生成的页面中画板名称过长时样式错误

### ISSUE THREAD

**Issue by tankxu** [utom/sketch-measure#58]
较长的画板名会折行贴到下一个画板上

![issue](https://cloud.githubusercontent.com/assets/5106039/9300448/a5f1cbd2-44f8-11e5-810e-c249cfe3681d.png)

**Comment by utom** [comment]
英文格式一般都是一个单词不换行, 我觉得你可以把下划线(_), 换成分割线(-)

**Comment by tankxu** [comment]
换成「-」可行，感谢
