### ISSUE TITLE
Can't add more properties

### ISSUE THREAD

**Issue by alyssatucker** [utom/sketch-measure#59]
I love this plugin but am encountering an issue. I've already used it to annotate much of my design, however now when I go to get properties of something, nothing happens. I use  ⌃ + ⇧ + 4  and the box for properties does not appear at all. It doesn't work when I go to the plugins menu rather than using the shortcuts either.

I'm attaching a gif showing that I'm able to get the size of an element but not the properties.

![measureproperties](https://cloud.githubusercontent.com/assets/4194009/9371948/ecf9ccc8-468d-11e5-8bd7-46e9ab1ab328.gif)

**Comment by alyssatucker** [comment]
I'm finding this just happens randomly. I got it working again.

**Comment by utom** [comment]
world you share your .sketch file let me test

**Comment by alyssatucker** [comment]
Unfortunately no, cause that could get me in trouble at work. Sorry.

**Comment by utom** [comment]
You have to try new update plugin and test. Maybe is working
