### ISSUE TITLE
Doesn't work export in the Sketch 55.2 and Sketch-measure 2.7.7

### ISSUE THREAD

**Issue by LenaAlyanova** [utom/sketch-measure#597]
hi
After update programms I have problem with export. Can you help me  with it?

**Comment by Mhywdotcom** [comment]
I just get it works again!!!
Download the latest version 2.8.0 from here: https://github.com/ellunium/sketch-measure-latest
install, restart sketch, and it works!

**Comment by LenaAlyanova** [comment]
hi
We just uninstalled plugin, and upload new version. It still is not working

**Comment by LenaAlyanova** [comment]
![зображення](https://user-images.githubusercontent.com/43852315/60002479-64e96900-9671-11e9-88a1-a2cab67d4b37.png)

**Comment by Jeason0228** [comment]
> I just get it works again!!!
> Download the latest version 2.8.0 from here: https://github.com/ellunium/sketch-measure-latest
> install, restart sketch, and it works!

@LenaAlyanova try this

**Comment by LenaAlyanova** [comment]
Thank you!  It is work!
