### ISSUE TITLE
Issue with symbols prevents spec export

### ISSUE THREAD

**Issue by centerofme** [utom/sketch-measure#620]
Measure is incompatible with sketch 58.  
Also consider a.) fixing your donate link or b.) getting a patreon so this plugin can be maintained regularly

**Comment by chensin** [comment]
How to do?

**Comment by centerofme** [comment]
I'm not sure.. i'm trying to find out whatever i can to answer what "*** -[__NSArrayM objectAtIndex:]: index 51 beyond bounds [0 .. 50]" means... well... more specifically where it's coming from.

**Comment by kiwimagic** [comment]
@centerofme I am running Sketch 58 and using the latest from @ellunium branch of Sketch Measure.  See https://github.com/ellunium/sketch-measure-latest.  I am operating fine using his branch after recently updating to Sketch 58.  [I do not use notes/comments or the toolbar for all those who have historically noted issues with them] 

which version of sketch measure are you running?

Thanks again to Ellunium for stepping in and helping us all out by getting that branch updated periodically!

**Comment by centerofme** [comment]
I actually found part of the problem ... we're using some pretty advanced symbols and detaching them actually made it run smoothly ... i'm going to continue looking into the issue to see if i can specifically narrow down what it was about the symbol that makes the plugin crash.

**Comment by centerofme** [comment]
I closed this for now... our design system has a bunch of overrides being used when you copy symbols - something in there is causing an error with this plugin.  this doesn't allow for me to upload a sketch file otherwise i'd give you guys something you could test with.
