### ISSUE TITLE
Feature Request: rem (relative em) unit support

### ISSUE THREAD

**Issue by careylin** [utom/sketch-measure#63]
I **love** this plugin and have gotten half of my team to use it and I'd love to get them all on board. The biggest hangup we face is the measurement units. 
For mobile apps we use **dp** and **px** (awesome) but for web we use **rems**. We handoff all of our web redlines with the sizes and spacing in rems, and its a bit of a hassle to go back and change all of the pixel values to rems. It would be amazing to have the support in the form of perhaps a toggle to change units. It's great that this plugin supports percentages, maybe all the units can be grouped in a settings modal, allowing you to switch units easily. Additionally rem units are base 16 out of the box, but it might be more flexible of a tool if you can redefine the base. Thoughts? Thanks!

**Comment by jdrewsmith** [comment]
This would be huge for my work as well! +1

**Comment by NateBaldwinDesign** [comment]
Most of the industry should be moving to rems (pixels are so 2005 ;-))  I second this request very enthusiastically!

**Comment by utom** [comment]
ADDED~

**Comment by jdrewsmith** [comment]
Is it possible to add rem support with a 16px base unit? That is the standard at my company. If it were editable that would be even better!

**Comment by devgonz** [comment]
I am also looking for a way to change to a 16px base unit.

**Comment by sunnythaper** [comment]
@utom I'm sorry for my ignorance as I do not frequent this issue board but added in what way? As of today I do not see this as a possibility in Sketch. I absolutely love Sketch and it's goal to allow for completely collaborative and cross-disciplinary design systems but for that for be fully realized, I believe relative units that reference a single base font-size has to be implemented. Neither px units or % can be applicable uniformly from small watch-sized resolutions to giant widescreen desktop monitors and beyond. We must also account for the substantial percentage of users that change their base font-size and be able to communicate the interface in that scenario to our developer friends. Please implement this feature, it will surely help us at my company in Arizona. I believe it would massively help others as well. Thanks for reading my novel.
