### ISSUE TITLE
Can I upload the html files online within sketch-measure? 

### ISSUE THREAD

**Issue by anyexinglu** [utom/sketch-measure#645]
Currently, sketch-measure can save sketch aboard into html files, so we can inspect all the design details offline.

But inspecting offline doesn't meet our common use, alternatively, we often need to share the files online with single link.

If it's possible to upload the generated output immediately? Or if can we implement it by ourselves, any guides?

**Comment by superjunaid** [comment]
I've uploaded the exports to internal web server so developers can take a look at the mockups. I don't think there's an issue if you uploaded your code/export specs.

**Comment by anyexinglu** [comment]
I've got it, thx!
