### ISSUE TITLE
Plugin does not work with OS Catalina 

### ISSUE THREAD

**Issue by LenaAlyanova** [utom/sketch-measure#648]
I can not see name's style after export  on new OS MAC (Catalina) 

My version of sketch 58
Can you help me, please  ?
<img width="216" alt="зображення" src="https://user-images.githubusercontent.com/43852315/71439249-88b16880-2701-11ea-9b65-8ce69f64514f.png">

**Comment by JacqueH** [comment]
Try https://github.com/ellunium/sketch-measure-latest instead

**Comment by LenaAlyanova** [comment]
I have a trouble 
<img width="248" alt="зображення" src="https://user-images.githubusercontent.com/43852315/71975803-867cfd00-321d-11ea-8cb5-38393219a00c.png">


> Try https://github.com/ellunium/sketch-measure-latest instead

**Comment by LenaAlyanova** [comment]
> I have a trouble
> <img alt="зображення" width="248" src="https://user-images.githubusercontent.com/43852315/71975803-867cfd00-321d-11ea-8cb5-38393219a00c.png">
> 
> > Try https://github.com/ellunium/sketch-measure-latest instead

I fixed it, thank you !!
Version 2.8.0 is working
