### ISSUE TITLE
Sketch 64 Tint support

### ISSUE THREAD

**Issue by girafic** [utom/sketch-measure#656]
![Bildschirmfoto 2020-03-24 um 11 19 28](https://user-images.githubusercontent.com/1187276/77415240-7c04e500-6dc2-11ea-83e3-02f1c52caa6d.png)

**Comment by qjebbs** [comment]
@girafic https://github.com/qjebbs/sketch-meaxure

**Comment by girafic** [comment]
@qjebbs thx for rewriting sketch measure 👍
