### ISSUE TITLE
Include 'Text Style' name in 'Get Property' output

### ISSUE THREAD

**Issue by katywebster** [utom/sketch-measure#68]
This plug-in is very useful - it would be EVEN more useful if you could include any 'Text Style' names in the 'Get Property' output. I have Text Styles set up which the developers use in a style library, which means they don't want to know the font names and sizes - they want the Text Style names!

Many thanks,
Katy

**Comment by jdrewsmith** [comment]
+1 to that

**Comment by awt2542** [comment]
+1 👍

**Comment by devgonz** [comment]
+1 Our developer asked for this as well.

**Comment by utom** [comment]
Update last version and 'Get Property' > 'Style name'

**Comment by bklaydman** [comment]
That for fast!!! Thank you!!!
