### ISSUE TITLE
No working in sketch 69.2

### ISSUE THREAD

**Issue by yangbe** [utom/sketch-measure#688]
![image](https://user-images.githubusercontent.com/9880101/98671622-81359500-238f-11eb-95b8-f38d4f3369ea.png)

**Comment by clonge** [comment]
Same here and for two other devs, it looks like it's universal.

**Comment by googincheng** [comment]
@yangbe 
https://github.com/googincheng/C-Measure

**Comment by yangbe** [comment]
> @yangbe
> https://github.com/googincheng/C-Measure

I had used this plugin, but there is another question

**Comment by googincheng** [comment]
> > @yangbe
> > https://github.com/googincheng/C-Measure
> 
> I had used this plugin, but there is another question

Try this, another great repo from @qjebbs https://github.com/qjebbs/sketch-meaxure
