### ISSUE TITLE
Spec Export slices thumbnails blank (3.4.2)

### ISSUE THREAD

**Issue by jaminroe** [utom/sketch-measure#74]
The thumbnails in the Slices tab are black:

<img width="243" alt="screen shot 2015-11-23 at 8 54 10 pm" src="https://cloud.githubusercontent.com/assets/1559447/11355619/605875f2-9224-11e5-9202-109095b56b91.png">

**Comment by haker2001** [comment]
Hello,

How do you export the slices? Do you export them separately and add them in the slice folder? What is the flow for that?

Thanks in advanced!
