### ISSUE TITLE
The plugin measure in different window

### ISSUE THREAD

**Issue by badyqb** [utom/sketch-measure#75]
It happens few times where the scnario is like this. I open two sketch files A & B. I wanted the measure the objects in window A, but after I use the shortcut:
1. there is delay/ lag before it generates
2. It doesn't generate in the file/ objects I want, instead for this case it generates in window B.

Current solution I have is just close both/ one of the sketch file and reopen again.

**Comment by utom** [comment]
True for every plugin. Fixed in 3.4.3 :)
