### ISSUE TITLE
Add support for preserving line breaks in Comments

### ISSUE THREAD

**Issue by damenleeturks** [utom/sketch-measure#79]
There ought to be an easier way to put line breaks in comments (other than manually editing the HTML :smiley:),

*As written in Sketch.app:*
![as written in sketch](https://cloud.githubusercontent.com/assets/259759/12247137/d9d28442-b86f-11e5-8414-241bb8cae2c6.png)

*As rendered in the export:*
![as exported](https://cloud.githubusercontent.com/assets/259759/12247139/dc478a1a-b86f-11e5-975f-c80b0b3b3121.png)

Then, in order to fix it, I have to find that section of the `html` file and add in line breaks like this: 
![editing](https://cloud.githubusercontent.com/assets/259759/12248206/15ad8db8-b875-11e5-9ff0-8768eca6852f.gif)

**Comment by utom** [comment]
added
