### ISSUE TITLE
export with an empty folder 

### ISSUE THREAD

**Issue by guyenner** [utom/sketch-measure#81]
i updated to sketch Version 3.5 (25232) and this is what isee: 
![screen shot 2016-01-26 at 1 52 00 pm](https://cloud.githubusercontent.com/assets/8269454/12591060/03740c74-c434-11e5-881e-30e79a2dc854.png)

**Comment by swidnikk** [comment]
me too :/

**Comment by utom** [comment]
I'm very anxious!!! because I am on holiday.

**Comment by swidnikk** [comment]
Oh no! and github does not have a 'on holiday' button :/ enjoy! I will poke
in the code to see if it is something trivial

**Comment by pinakeenaik** [comment]
Is there a solution to this! Need it urgently!

**Comment by joaobborges** [comment]
same problem here :/ if anyone know a solution feel free to share :dancers:

**Comment by swidnikk** [comment]
Tried to poke in the code but I couldn't figure how to debug...

**Comment by utom** [comment]
fixed!

**Comment by pinakeenaik** [comment]
Still won't work for me!

**Comment by utom** [comment]
@pinakeenaik what's sketch version

**Comment by pinakeenaik** [comment]
Version 3.5.1 (25234)

**Comment by utom** [comment]
try download plugin last version

**Comment by pinakeenaik** [comment]
Thanks a tonne! You are a saviour!
