### ISSUE TITLE
Measure spacing often not working and it produces weird text value

### ISSUE THREAD

**Issue by badyqb** [utom/sketch-measure#89]
When I open my document that already has measurement, and I try to measure other elements (distance) it won't work. 

1.  Beside that now I have to create artboard to have a measurement (I hope I can measure outside artboard too)
2. If I already have an artboard that has a measurement, I can't measure on another artboard
3. It produces weird text somewhere outside the artboard

Here's the video of the bug: http://recordit.co/hzcwyzGKfQ

**Comment by utom** [comment]
update last version
