### ISSUE TITLE
Doesn't work with  3.5.2

### ISSUE THREAD

**Issue by mikearndt** [utom/sketch-measure#90]
None of sketch measure works for me correctly on 3.5.2. Bellow are some recordings of what happens.

![screenshot 2016-02-11 09 26 09](https://cloud.githubusercontent.com/assets/2023250/12984276/d60bb03c-d0a1-11e5-8cbd-231a845400ec.png)

![screen recording 2016-02-11 at 09 31 am](https://cloud.githubusercontent.com/assets/2023250/12984390/533c5980-d0a2-11e5-8bc6-ef8f8f3e6201.gif)
![screen recording 2016-02-11 at 09 07 am](https://cloud.githubusercontent.com/assets/2023250/12984260/c8b7d0aa-d0a1-11e5-8440-134230c82eec.gif)
![screen-recording-2016-02-11-at-09 09-am](https://cloud.githubusercontent.com/assets/2023250/12984261/c8b8d266-d0a1-11e5-84b6-0991735c881f.gif)

**Comment by utom** [comment]
Update last version

**Comment by pmakro** [comment]
Yep, that worked for me

**Comment by mikearndt** [comment]
Worked, thanks.
