### ISSUE TITLE
Last version problem

### ISSUE THREAD

**Issue by quaritexa** [utom/sketch-measure#91]
Last version of Measure works on my Sketch 3.4.4 just once. Where I can find Measure for my version of Sketch?

**Comment by iphotostuff** [comment]
Same issue here. OSX 10.9.5, Sketch 3.4.4 only creates one property measurement. After that, anytime I try to use the plugin nothing happens. I have tried to quit and return from Sketch with no success. Two of my coworkers have the same issue.

**Comment by utom** [comment]
Sorry, It's not working in 3.4.4. Please update you Sketch.app :D

**Comment by quaritexa** [comment]
I can't update yet. I have Mavericks.
