### ISSUE TITLE
Does not work with Sketch 3.6 Beta

### ISSUE THREAD

**Issue by bomberstudios** [utom/sketch-measure#93]
Hi there,

we're pretty close to releasing Sketch 3.6, and while testing plugins we discovered that measure is not working correctly there.

The problem seems to be that `resizeRoot` has been removed from the API (see the thread at http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2016-January/001747.html for more info)

I'll send you a pull request that fixes it in a minute.

**Comment by bomberstudios** [comment]
Ah, I was testing an outdated version : (

Works fine now, sorry about the noise!

**Comment by SUPK187** [comment]
@bomberstudios Thank you for having tested the script before releasing Sketch 3.6 : )

**Comment by bomberstudios** [comment]
@SUPK187 my pleasure : )

**Comment by utom** [comment]
@bomberstudios Cool, I like you
