### ISSUE TITLE
Shortcuts disappearance

### ISSUE THREAD

**Issue by sarahlafeuil-aufem** [utom/sketch-measure#94]
Hi

Thank you so much for this great plugin. It's so helpfull and easy to use !

I have a small problem with the first 3 shortcuts : 
1- create overlay
2- measure size
3- measure overlay

On the first launch, it works perfectly, I can see the shortcuts in the menu. 
Then, they disappear and I can't use them anymore. I don't know why, I tried several uninstall/reinstall.
No clue at all...

Thank you for your help !

**Comment by girafic** [comment]
@sarahlafeuil-aufem: is the plugin Craft on your system?

**Comment by sarahlafeuil-aufem** [comment]
@girafic Yes, and it automatically update.

**Comment by digin8** [comment]
It seems Craft interrupts Sketch Measure's keyboard shortcuts. I originally tried to change the keyboard shortcuts to ⌥ ⇧(number) using the instructions provided but they seemed to reset themselves after a while. Toggling Craft off doesn't seem to fix this issue. 

However, I have now changed the shortcut to ⌥ ⇧ ⌘(number) and that seems to be working fine now.

**Comment by utom** [comment]
To create your own custom shortcuts, go to Keyboard in your System Preferences and click the Shortcuts tab. Select App Shortcuts and click ‘+’ to create a new shortcut. Choose Sketch from the Application list, then enter the exact name of the menu item you want to create the shortcut for. Finally choose your own shortcut combination and you’re all set.

**Comment by utom** [comment]
Create Custom Shortcuts in mac keyboard

**Comment by ahsanpervaiz** [comment]
For me after setting custom shortcuts, old shortcuts came back and still its not working so i have uninstalled it. Please fix this issue
